import {saveOrganicReport} from './organic-rankings.mjs';
import {parseCSV,encodeCSV} from './core/csv.mjs';
export const OWN_DOMAIN='nosweatusa.com';
export function domain(value){const v=String(value||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'').replace(/^www\./,'');if(v.length>253||!/^([a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$/.test(v))throw new Error('Geçerli bir alan adı girin.');return v;}
export function suiteState(state){return state.seoSuite||={settings:{keywords:[],competitors:[],auto:false,providerAuto:false},ranks:[],domainReports:{},keywords:null,backlinks:null,audits:[],digests:[],alerts:[],runs:[]};}
export function suiteSettings(state,input){const s=suiteState(state);const keywords=[...new Set(String(input.keywords||'').split('\n').map(x=>x.trim().toLowerCase()).filter(Boolean))];if(keywords.length>10||keywords.some(k=>k.length>80||k.split(/\s+/).length>10))throw new Error('En fazla 10 ifade; her biri 80 karakter ve 10 kelimeyi aşmamalıdır.');const competitors=[...new Set(String(input.competitors||'').split('\n').map(x=>x.trim()).filter(Boolean).map(domain))];if(competitors.length>3||competitors.includes(OWN_DOMAIN))throw new Error('Kendi siteniz dışında en fazla 3 rakip seçin.');s.settings={keywords,competitors,auto:input.auto==='true',providerAuto:input.providerAuto==='true'};}
function num(value,max=1e12){if(value===''||value===null||value===undefined)return null;const n=Number(String(value).replace(/,/g,''));if(!Number.isFinite(n)||n<0||n>max)throw new Error('Sayısal değer geçersiz.');return n;}
function url(value){if(!value)return '';const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port)throw new Error('URL geçersiz.');return u.href;}
function date(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value||value>new Date().toISOString().slice(0,10))throw new Error('Geçerli, gelecekte olmayan veri tarihi seçin.');return value;}
export function importSuiteCSV(state,input){
 const s=suiteState(state);if(typeof input.csv!=='string'||new TextEncoder().encode(input.csv).length>2_000_000)throw new Error('CSV en fazla 2 MB olabilir.');
 const raw=parseCSV(input.csv);
 const aliases={'search volume':'volume','keyword difficulty':'difficulty','keyword difficulty %':'difficulty','traffic cost':'traffic_cost','keyword intents':'intent','position type':'position_type'};
 const rows=input.kind==='organic'?raw.map(row=>{const entries=Object.entries(row).map(([k,v])=>[aliases[k.trim().toLowerCase()]||k.trim().toLowerCase(),v]);if(new Set(entries.map(e=>e[0])).size!==entries.length)throw new Error('CSV sütunları aynı metriğe birden fazla kez eşleşiyor.');return Object.fromEntries(entries);}):raw;if(rows.length>2000)throw new Error('En fazla 2000 satır yükleyin.');const observedAt=date(input.date),provider=String(input.provider||'CSV').trim().slice(0,80)||'CSV';const meta={observedAt,provider,country:'us',language:'en',importedAt:new Date().toISOString(),limited:true};
 const required={organic:['keyword','position','url'],ranks:['keyword','device','position','url'],gaps:['keyword','position'],keywords:['keyword','volume','difficulty'],backlinks:['source_url','target_url','status']}[input.kind];
 if(!required||required.some(k=>!Object.hasOwn(rows[0],k)))throw new Error('CSV sütunları seçilen şablonla eşleşmiyor.');
 const normalized=rows.map((r,i)=>{try{
  if(input.kind==='backlinks'){const source=url(r.source_url),target=url(r.target_url);if(!source||!target||domain(new URL(target).hostname)!==OWN_DOMAIN||domain(new URL(source).hostname)===OWN_DOMAIN||!['active','new','lost'].includes(r.status))throw new Error('Backlink hedefi veya durumu geçersiz.');return {source,target,status:r.status,anchor:String(r.anchor||'').slice(0,500)};}
  if(input.kind==='organic'&&r.position_type&&r.position_type.toLowerCase()!=='organic')throw new Error('Yalnızca organik pozisyonları dışa aktarın.');
  const keyword=String(r.keyword||'').trim().toLowerCase();if(!keyword||keyword.length>150)throw new Error('Anahtar kelime geçersiz.');
  if(input.kind==='ranks'){if(!['mobile','desktop'].includes(r.device))throw new Error('device: mobile veya desktop olmalı.');const position=num(r.position,100);if(position!==null&&(!Number.isInteger(position)||position<1))throw new Error('Konum 1–100 veya boş olmalı.');const target=url(r.url);if(target&&domain(new URL(target).hostname)!==OWN_DOMAIN)throw new Error('URL mağazaya ait olmalı.');return {keyword,device:r.device,position,url:target};}
  const position=num(r.position,input.kind==='organic'?100:1000);if(['gaps','organic'].includes(input.kind)&&(!Number.isInteger(position)||position<1))throw new Error(input.kind==='organic'?'Sıralama 1–100 olmalı.':'Sıralama 1–1000 olmalı.');if(input.kind==='organic'&&(!r.url||domain(new URL(url(r.url)).hostname)!==OWN_DOMAIN))throw new Error('URL mağazaya ait olmalı.');return {keyword,position,volume:num(r.volume),difficulty:num(r.difficulty,100),url:url(r.url),...(input.kind==='organic'?{traffic:num(r.traffic),trafficCost:num(r.traffic_cost),cpc:num(r.cpc),intent:['informational','commercial','transactional','navigational'].includes(r.intent)?r.intent:null}:{} )};
 }catch(e){throw new Error(`Satır ${i+2}: ${e.message}`);}});
 const identities=normalized.map(r=>input.kind==='backlinks'?`${r.source}|${r.target}`:`${r.keyword}|${r.device||''}`);if(new Set(identities).size!==identities.length)throw new Error('CSV içinde yinelenen satır var.');
 const report={...meta,rows:normalized};
 if(input.kind==='ranks'){s.ranks=s.ranks.filter(r=>r.observedAt!==observedAt||r.provider!==provider);s.ranks.push(report);s.ranks.sort((a,b)=>a.observedAt.localeCompare(b.observedAt));s.ranks=s.ranks.slice(-60);}
 if(input.kind==='gaps'){const target=domain(input.domain);if(![OWN_DOMAIN,...s.settings.competitors].includes(target))throw new Error('Önce rakibi ayarlara ekleyin.');s.domainReports[target]={...report,domain:target,device:'desktop'};}
 if(input.kind==='organic'){const organic={...report,domain:OWN_DOMAIN,device:'desktop'};saveOrganicReport(s,organic);s.domainReports[OWN_DOMAIN]=organic;}
 if(input.kind==='keywords')s.keywords=report;
 if(input.kind==='backlinks')s.backlinks=report;
 return normalized.length;
}
export function keywordGap(s){const own=s.domainReports[OWN_DOMAIN];if(!own)return [];const index=new Map(own.rows.map(r=>[r.keyword,r]));const result=[];for(const d of s.settings.competitors){const report=s.domainReports[d];if(!report||report.provider!==own.provider||report.observedAt!==own.observedAt||report.country!==own.country||report.language!==own.language||report.device!==own.device)continue;for(const r of report.rows){const a=index.get(r.keyword);if(!a||a.position>r.position)result.push({...r,domain:d,ownPosition:a?.position??null,kind:a?'Rakip daha üstte':'Kendi raporunda bulunamadı'});}}return result.sort((a,b)=>(b.volume||0)-(a.volume||0)).slice(0,500);}
export function rankChanges(s){const latest=s.ranks.at(-1);if(!latest)return [];const previous=[...s.ranks].reverse().find(r=>r.observedAt<latest.observedAt&&r.provider===latest.provider&&r.country===latest.country&&r.language===latest.language);const before=new Map(previous?.rows.map(r=>[`${r.keyword}|${r.device}`,r])||[]);return latest.rows.map(r=>{const p=before.get(`${r.keyword}|${r.device}`);return {...r,previous:p?.position??null,change:r.position!==null&&p?.position!=null?p.position-r.position:null};});}
export function reportCSV(s){return encodeCSV([['Tarih','Bölüm','Öğe','Değer','Kaynak'],...s.ranks.flatMap(r=>r.rows.map(k=>[r.observedAt,'Sıralama',`${k.keyword} (${k.device})`,k.position??'İlk 100 içinde bulunamadı',r.provider])),...(s.keywords?.rows||[]).map(k=>[s.keywords.observedAt,'Arama hacmi',k.keyword,k.volume??'Bilinmiyor',s.keywords.provider]),...(s.alerts||[]).map(a=>[a.at,'Uyarı',a.title,a.detail,'NOWUSA'])]);}
export const suiteTemplates={organic:'keyword,position,url,volume,difficulty,traffic,traffic_cost,cpc,intent\n',ranks:'keyword,device,position,url\n',gaps:'keyword,position,volume,difficulty,url\n',keywords:'keyword,volume,difficulty\n',backlinks:'source_url,target_url,status,anchor\n'};
