# Link this project to the registered app with `shopify app config link`.
client_id = "15dad9f47a0fae6a2d46cf6c02946492"
name = "No Sweat SEO"
application_url = "https://your-app-host.example"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,write_products,read_files,write_files"

[auth]
redirect_urls = ["https://your-app-host.example/auth/callback"]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]
