import {useState} from 'react';
import {defaultAuditConfig} from '../lib/audit-config.mjs';
import type {ActionInput} from '../lib/types';
export type AuditConfig=typeof defaultAuditConfig;
const steps=['Genel','Tarayıcı','İzin / engelleme kuralları','URL parametreleri','Kısıtlamalar'];
export default function AuditWizard({initial,busy,canManage,onAction,onClose}:{initial?:AuditConfig;busy:boolean;canManage:boolean;onAction:(input:ActionInput)=>void;onClose:()=>void}){
 const [step,setStep]=useState(0),[c,setC]=useState<AuditConfig>({...defaultAuditConfig,...initial});
 const change=<K extends keyof AuditConfig>(key:K,value:AuditConfig[K])=>setC({...c,[key]:value});
 return <section className="audit-wizard" aria-label="Yeni site denetimi"><div className="audit-wizard-heading"><div><h2>Yeni denetim</h2><p>Kapsamı ve tarama kurallarını belirleyin.</p></div><s-button onClick={onClose} disabled={busy}>Kapat</s-button></div><div className="audit-wizard-layout"><nav aria-label="Denetim adımları">{steps.map((label,i)=><button key={label} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined}><b>{i+1}</b><span>{label}{i>0&&<small>İsteğe bağlı</small>}</span></button>)}</nav><div className="audit-wizard-fields"><h3>{step+1}. {steps[step]}</h3><s-stack direction="block" gap="base">
 {step===0&&<><s-text-field label="Denetim adı" value={c.name} maxLength={80} onInput={e=>change('name',e.currentTarget.value)}/><s-select label="Mağaza alan adı" value={c.host} onChange={e=>change('host',e.currentTarget.value)}><s-option value="nosweatusa.com">nosweatusa.com</s-option><s-option value="www.nosweatusa.com">www.nosweatusa.com</s-option></s-select><s-select label="En fazla taranacak sayfa" value={String(c.maxPages)} onChange={e=>change('maxPages',Number(e.currentTarget.value))}><s-option value="10">10 sayfa</s-option><s-option value="30">30 sayfa</s-option><s-option value="60">60 sayfa</s-option></s-select><s-select label="URL kaynağı" value={c.source} onChange={e=>change('source',e.currentTarget.value)}><s-option value="site">Site + katalog + site haritası</s-option><s-option value="sitemap">Site haritası + keşfedilen bağlantılar</s-option><s-option value="urls">Yalnızca verdiğim URL listesi</s-option></s-select>{c.source==='urls'&&<s-text-area label="Başlangıç URL’leri (satır başına bir HTTPS URL)" value={c.urls} rows={5} onInput={e=>change('urls',e.currentTarget.value)}/>}<p>Yalnızca bu mağazanın herkese açık sayfaları. Yönetim, hesap ve ödeme yolları taranmaz.</p></>}
 {step===1&&<><s-select label="Tarayıcı kimliği" value={c.device} onChange={e=>change('device',e.currentTarget.value)}><s-option value="mobile">NOWUSA Mobile</s-option><s-option value="desktop">NOWUSA Desktop</s-option></s-select><s-select label="İstekler arası bekleme" value={String(c.delayMs)} onChange={e=>change('delayMs',Number(e.currentTarget.value))}><s-option value="0">Bekleme yok (sıralı istek)</s-option><s-option value="500">0,5 saniye</s-option><s-option value="1000">1 saniye</s-option><s-option value="2000">2 saniye</s-option></s-select><p>Sunucu HTML taraması yapılır; mobil/masaüstü seçimi User-Agent başlığını değiştirir. JavaScript tarayıcıda çalıştırılmaz. Bir denetim en fazla 3 dakika sürer.</p></>}
 {step===2&&<><s-text-area label="İzin verilen yollar" value={c.allow} rows={4} placeholder="/products/" onInput={e=>change('allow',e.currentTarget.value)}/><s-text-area label="Engellenen yollar" value={c.disallow} rows={4} placeholder="/collections/*/products/" onInput={e=>change('disallow',e.currentTarget.value)}/><p>Her satıra / ile başlayan bir yol yazın. * jokeri desteklenir; kurallar yolun başlangıcından eşleşir. Engelleme önceliklidir. İzin listesi boşsa tüm güvenli mağaza yolları değerlendirilir.</p></>}
 {step===3&&<><s-checkbox label="Tüm URL parametrelerini kaldır" checked={c.removeAllParams} onChange={e=>change('removeAllParams',e.currentTarget.checked)}/><s-text-area label="Kaldırılacak parametreler" value={c.removeParams} disabled={c.removeAllParams} rows={5} onInput={e=>change('removeParams',e.currentTarget.value)}/><p>Örnek: utm_*, gclid, fbclid (satır başına bir). Tümünü kaldır seçimi kapalıysa diğer parametreler korunur. URL’ler sıralanıp yinelenenler tekilleştirilir.</p></>}
 {step===4&&<><s-checkbox label="Kendi mağazamda robots.txt engellerini bu denetim için geçersiz kıl" checked={c.ignoreRobots} onChange={e=>change('ignoreRobots',e.currentTarget.checked)}/><s-checkbox label="nofollow işaretli dahili bağlantıları da takip et" checked={c.followNofollow} onChange={e=>change('followNofollow',e.currentTarget.checked)}/><p>Bu seçenekler mağazanın robots.txt veya HTML dosyalarını değiştirmez. Parola, CAPTCHA ve güvenlik duvarları aşılmaz; bu sayfalar erişilemedi olarak raporlanır.</p><div className="suite-summary"><strong>{c.name}</strong><p>{c.host} · en fazla {c.maxPages} sayfa · {c.device==='mobile'?'Mobil':'Masaüstü'} · {c.delayMs} ms bekleme</p><p>robots.txt: {c.ignoreRobots?'bu denetimde geçersiz':'uygulanacak'} · Parametreler: {c.removeAllParams?'kaldırılacak':'seçilen kurallara göre'}</p></div></>}
 </s-stack><div className="audit-wizard-actions">{step>0&&<s-button disabled={busy} onClick={()=>setStep(step-1)}>Geri</s-button>}{step<4?<s-button variant="primary" onClick={()=>setStep(step+1)}>Devam</s-button>:<><s-button disabled={busy||!canManage} onClick={()=>onAction({intent:'suite-audit-settings',config:JSON.stringify(c)})}>Ayarları kaydet</s-button><s-button variant="primary" disabled={busy||!canManage||!c.name.trim()} onClick={()=>onAction({intent:'suite-audit',config:JSON.stringify(c)})}>Kaydet ve denetimi başlat</s-button></>}</div></div></div></section>;
}
