import {useState} from 'react';
import type {ActionInput,Dashboard} from '../lib/types';
import './backlinks.css';

type Props={data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void};
const statuses:Record<string,string>={found:'Bağlantı bulundu',mention:'Bağlantısız anılma',missing:'Bağlantı bulunamadı',unchecked:'Kontrol bekliyor',unknown:'Sonuç belirsiz'};
const host=(url:string)=>{try{return new URL(url).hostname;}catch{return url;}};
const checked=(value:string|null)=>value?new Date(value).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})+' UTC':'Henüz kontrol edilmedi';

export default function BacklinksPanel({data,busy,onAction}:Props){
 const [url,setURL]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[limit,setLimit]=useState(25);
 const sources=data.backlinks||[];
 const matches=sources.filter(b=>(status==='all'||b.status===status)&&`${b.url} ${b.links.map(l=>l.anchor).join(' ')}`.toLocaleLowerCase('tr-TR').includes(query.trim().toLocaleLowerCase('tr-TR')));
 let valid=false;try{const parsed=new URL(url.trim());valid=['http:','https:'].includes(parsed.protocol)&&Boolean(parsed.hostname);}catch{/* Incomplete URL while typing. */}
 const metrics=[{label:'Takip edilen kaynak',value:sources.length,icon:'link'},{label:'Bağlantı bulunan',value:sources.filter(b=>b.status==='found').length,icon:'check-circle'},{label:'Bağlantısız anılma',value:sources.filter(b=>b.status==='mention').length,icon:'text'},{label:'Kontrol bekleyen',value:sources.filter(b=>b.status==='unchecked').length,icon:'clock'}] as const;
 return <div className="backlinks-panel" aria-busy={busy}>
  <div className="backlinks-heading"><div><h2>Backlink takibi</h2><p>Mağazanıza bağlantı veren sayfaları tek yerden izleyin.</p></div><s-button variant="primary" disabled={busy||!sources.length} onClick={()=>onAction({intent:'backlink-check'})}>Kaynakları kontrol et</s-button></div>
  <div className="backlinks-metrics">{metrics.map(m=><div key={m.label}><s-icon type={m.icon}/><span>{m.label}</span><strong>{m.value.toLocaleString('tr-TR')}</strong></div>)}</div>
  <section className="backlinks-card" aria-labelledby="backlinks-add-title"><div className="backlinks-card-heading"><h3 id="backlinks-add-title">Kaynak ekle</h3><span className="backlinks-caption">API bağlantısı gerekmez</span></div><p className="backlinks-caption">Bağlantınızı kontrol etmek istediğiniz harici yazının veya sayfanın tam adresini ekleyin.</p><form className="backlinks-add" onSubmit={e=>{e.preventDefault();if(valid&&!busy)onAction({intent:'backlink-add',url:url.trim()});}}><s-url-field label="Harici kaynak URL’si" value={url} onInput={e=>setURL(e.currentTarget.value)} placeholder="https://example.com/article"/><s-button type="submit" variant="primary" disabled={busy||!valid}>Takibe ekle</s-button></form><div className="backlinks-auto"><s-checkbox label="Her gün otomatik kontrol et" checked={data.backlinksAuto||false} disabled={busy} onChange={e=>onAction({intent:'backlink-auto',enabled:String(e.currentTarget.checked)})}/><span className="backlinks-caption">Günlük sunucu görevi çalıştığında yenilenir.</span></div></section>
  <section className="backlinks-card" aria-labelledby="backlinks-list-title"><div className="backlinks-card-heading"><h3 id="backlinks-list-title">İzlenen kaynaklar <span className="backlinks-count">{sources.length}</span></h3><span className="backlinks-caption">Sayfa bazında kontrol sonuçları</span></div>
   {sources.length>0&&<div className="backlinks-filters"><s-search-field label="Kaynak veya bağlantı metni ara" value={query} onInput={e=>{setQuery(e.currentTarget.value);setLimit(25);}}/><s-select label="Durum" value={status} onChange={e=>{setStatus(e.currentTarget.value);setLimit(25);}}><s-option value="all">Tüm durumlar</s-option>{Object.entries(statuses).map(([key,label])=><s-option key={key} value={key}>{label}</s-option>)}</s-select></div>}
   {!sources.length?<div className="backlinks-empty"><s-icon type="link" size="base"/><h4>İlk kaynağınızı ekleyin</h4><p>Mağazanızdan söz eden bir yazıyı ekleyin, ardından kaynakları kontrol edin. Bağlantı, hedef sayfa ve bağlantı özellikleri burada görünecek.</p><span>Başlangıç için aşağıdaki arama fırsatlarını kullanabilirsiniz.</span></div>:matches.length?<><p className="backlinks-caption" role="status">{matches.length} kaynak · {Math.min(limit,matches.length)} gösteriliyor</p>
{/* eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex -- Focus enables keyboard scrolling of the wide results table. */}
<div className="backlinks-table-scroll" tabIndex={0} role="region" aria-label="Backlink kaynak sonuçları"><table><thead><tr><th scope="col">Kaynak sayfa</th><th scope="col">Durum</th><th scope="col">Son kontrol</th><th scope="col">İşlem</th></tr></thead><tbody>{matches.slice(0,limit).map(b=><tr key={b.id}><td className="backlinks-source"><s-link href={b.url} target="_blank">{host(b.url)}</s-link><span className="backlinks-url">{b.url}</span><details className="backlinks-details"><summary>Bağlantı ayrıntıları{b.links.length?` (${b.links.length})`:''}</summary>{b.links.map((l,i)=><div className="backlinks-link-detail" key={`${l.url}-${i}`}><strong>{l.anchor||'Metinsiz bağlantı'}</strong><s-link href={l.url} target="_blank">{l.url}</s-link><span>Bağlantı özelliği: {l.rel||'nofollow / sponsored belirtilmemiş'}</span></div>)}{!b.links.length&&<p>Kaydedilmiş bağlantı ayrıntısı yok.</p>}{b.note&&<p>{b.note}</p>}</details></td><td><span className={`backlinks-status backlinks-status-${Object.prototype.hasOwnProperty.call(statuses,b.status)?b.status:'unknown'}`}>{statuses[b.status]||'Sonuç belirsiz'}</span></td><td className="backlinks-date">{checked(b.checkedAt)}</td><td><s-button variant="tertiary" disabled={busy} accessibilityLabel={`${host(b.url)} kaynağını listeden kaldır`} onClick={()=>onAction({intent:'backlink-delete',id:b.id})}>Kaldır</s-button></td></tr>)}</tbody></table></div>{matches.length>limit&&<s-button onClick={()=>setLimit(limit+25)}>25 kaynak daha göster</s-button>}</>:<div className="backlinks-empty"><h4>Eşleşen kaynak yok</h4><p>Başka bir ifade veya durum deneyin.</p><s-button onClick={()=>{setQuery('');setStatus('all');setLimit(25);}}>Filtreleri temizle</s-button></div>}
   <p className="backlinks-footnote">Yalnızca eklediğiniz kaynaklar kontrol edilir. “Bağlantı bulunamadı”, kontrol edilen HTML’de bağlantı bulunmadığını belirtir; tek başına kayıp backlink kanıtı değildir.</p>
  </section>
  <details className="backlinks-card backlinks-opportunities"><summary><s-icon type="search"/><span>Yeni backlink fırsatları bul</span><span className="backlinks-caption">Hazır aramalar</span><s-icon type="chevron-down"/></summary><p className="backlinks-caption">Aramayı yeni sekmede açın. Uygun bir yazı bulduğunuzda adresini yukarıdan takibe ekleyin.</p>{data.opportunities?.length?<div className="backlinks-opportunity-grid">{data.opportunities.map(o=><a key={o.query} href={o.url} target="_blank" rel="noopener noreferrer"><s-icon type="search"/><span>{o.query}</span><s-icon type="external"/></a>)}</div>:<p className="backlinks-caption">Hazır arama önerisi yok. Bildiğiniz bir kaynak adresini ekleyebilirsiniz.</p>}<p className="backlinks-footnote">Arama sonuçları otomatik alınmaz. Bu araç harici sitelerde hesap veya backlink oluşturmaz.</p></details>
 </div>;
}
