import {useState} from 'react';
import type {ActionInput,Dashboard,GrowthMetric,GrowthTask} from '../lib/types';
type Props={data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void;onEdit:(id:string)=>void;onNavigate:(section:string)=>void};
const fmt=(n:number)=>new Intl.NumberFormat('tr-TR').format(n);
const percent=(n:number)=>`${(n*100).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})}%`;
function MetricLine({value}:{value:GrowthMetric}){return <s-paragraph>{fmt(value.clicks)} tıklama · {fmt(value.impressions)} gösterim · {percent(value.ctr)} CTR · {value.position?.toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1})||'—'} ortalama konum</s-paragraph>;}
function OutreachEditor({data,busy,onAction}:Pick<Props,'data'|'busy'|'onAction'>){
 const [source,setSource]=useState(''),[pageId,setPageId]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[note,setNote]=useState('');
 const drafts=data.growth?.outreach||[];const backlink=data.backlinks?.find(b=>b.id===source);
 const selectSource=(id:string)=>{setSource(id);setNote('');const draft=drafts.find(d=>d.backlinkId===id);setPageId(draft?.pageId||'');setSubject(draft?.subject||'');setBody(draft?.body||'');};
 return <s-section heading="Backlink iletişim taslağı"><s-stack direction="block" gap="base"><s-paragraph>Takip ettiğiniz kaynağı ve uygun ürünü seçin. İngilizce metin taslağı hazırlayıp düzenleyebilirsiniz. Gönderim otomatik değildir.</s-paragraph><s-select label="Harici kaynak" value={source} onChange={e=>selectSource(e.currentTarget.value)}><s-option value="">Kaynak seç</s-option>{(data.backlinks||[]).map(b=><s-option key={b.id} value={b.id}>{b.url}{b.status==='mention'?' · linksiz qeyd':''}</s-option>)}</s-select><s-select label="Önerilecek ürün / koleksiyon" value={pageId} onChange={e=>setPageId(e.currentTarget.value)}><s-option value="">Sayfa seç</s-option>{data.catalog.pages.filter(p=>p.url).map(p=><s-option key={p.id} value={p.id}>{p.title}</s-option>)}</s-select><s-button disabled={busy||!backlink||!pageId} onClick={()=>onAction({intent:'growth-outreach',backlinkId:source,pageId})}>İngilizce taslak hazırla</s-button>
 {drafts.find(d=>d.backlinkId===source)&&<s-button disabled={busy} onClick={()=>{const d=drafts.find(d=>d.backlinkId===source)!;setSubject(d.subject);setBody(d.body);setPageId(d.pageId);}}>Kaydedilmiş taslağı düzenle</s-button>}
 <s-text-field label="E-posta konusu" value={subject} maxLength={200} onInput={e=>setSubject(e.currentTarget.value)}/><s-text-area label="İletişim metni" rows={8} value={body} maxLength={5000} onInput={e=>setBody(e.currentTarget.value)}/><s-stack direction="inline" gap="base"><s-button disabled={busy||!source||!pageId||!subject||!body} onClick={()=>onAction({intent:'growth-outreach',backlinkId:source,pageId,subject,body})}>Düzenlenen metni kaydet</s-button><s-button disabled={!body} onClick={async()=>{try{await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);setNote("Metin kopyalandı.");}catch{setNote("Tarayıcı kopyalamaya izin vermedi. Metni alandan seçip kopyalayın.");}}}>Metni kopyala</s-button></s-stack>{note&&<s-banner tone="info">{note}</s-banner>}
 {drafts.length>0&&<s-paragraph color="subdued">{drafts.length} kaydedilmiş taslak var. Kaynağı seçip taslağı düzenleyin. Alıcı adresini ve içeriğin uygunluğunu kontrol edin.</s-paragraph>}</s-stack></s-section>;
}
export default function GrowthPanel({data,busy,onAction,onEdit,onNavigate}:Props){
 const g=data.growth;const [focus,setFocus]=useState(''),[queryFilter,setQueryFilter]=useState('');if(!g)return null;
 const runTask=(t:GrowthTask)=>{if(t.section==='editor'&&t.pageId)onEdit(t.pageId);else if(t.section==='sync')onAction({intent:'sync'});else if(t.section==='checklist'){setFocus(t.pageId||'');document.getElementById('growth-checklist')?.scrollIntoView({behavior:'smooth'});}else if(t.section==='outreach')document.getElementById('growth-outreach')?.scrollIntoView({behavior:'smooth'});else onNavigate(t.section);};
 const product=g.products.find(p=>p.pageId===(focus||g.products[0]?.pageId));
 const queries=g.queries.filter(q=>(!focus||q.pageId===focus)&&`${q.query} ${q.pageTitle}`.toLowerCase().includes(queryFilter.toLowerCase()));
 return <s-stack direction="block" gap="base"><s-section heading="ABD’den müşteri kazanma"><s-stack direction="block" gap="base"><s-paragraph>ABD · Google Web araması · tüm cihazlar. Önce ilgili ziyaretçileri getirecek işleri seçin, ardından sonuçları takip edin.</s-paragraph><s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy||!data.google?.connected} onClick={()=>onAction({intent:'google-sync'})}>ABD verilerini güncelle</s-button><s-button onClick={()=>onNavigate("Google sonuçları")}>Google bağlantısını aç</s-button></s-stack>{!g.current?<s-banner tone="info">ABD için gerçek rapor yok. Google hesabını bağlayıp verileri getirin. Katalog kontrollerini şimdi de tamamlayabilirsiniz.</s-banner>:<><s-paragraph>{g.current.startDate} — {g.current.endDate} · {g.current.property}</s-paragraph><MetricLine value={g.current.totals}/>{g.previous&&<s-paragraph color="subdued">Önceki {g.previous.startDate} — {g.previous.endDate}: {fmt(g.previous.totals.clicks)} tıklama, {fmt(g.previous.totals.impressions)} gösterim. Tıklama farkı: {fmt(g.current.totals.clicks-g.previous.totals.clicks)}.</s-paragraph>}<s-paragraph color="subdued">Konum, dönem ortalamasıdır. Toplamlar Google’ın döndürdüğü sayfa satırlarına aittir; tüm trafiği ve satışları göstermez.</s-paragraph></>}{g.warnings.map(w=><s-banner key={w} tone="warning">{w}</s-banner>)}</s-stack></s-section>
 <s-section heading="Bu haftanın 3 temel işi"><s-paragraph color="subdued">Hafta: {g.week}. Sıralama, gözlemlenen sorunlara ve gösterimlere dayanır. Tamamlanan işin yerini sıradaki öncelik alır.</s-paragraph>{g.tasks.length?g.tasks.map(t=><div key={t.id} className="seo-growth-task"><div><s-heading>{t.title}</s-heading><s-paragraph>{t.detail}</s-paragraph></div><s-stack direction="inline" gap="base"><s-button disabled={busy} onClick={()=>runTask(t)}>İşe git</s-button><s-button disabled={busy} onClick={()=>onAction({intent:'growth-task',taskId:t.id,done:'true'})}>Tamamladım</s-button></s-stack></div>):<s-paragraph>Mevcut verilerde açık bir öncelik yok. Bu, tüm SEO çalışmalarının tamamlandığı anlamına gelmez.</s-paragraph>}{g.completed.map(t=><div className="seo-growth-task" key={t.id}><s-text>{t.title} — tamamlandı olarak işaretlendi</s-text><s-button disabled={busy} onClick={()=>onAction({intent:'growth-task',taskId:t.id,done:'false'})}>Yeniden aç</s-button></div>)}</s-section>
 <s-section heading="Tıklama artırma fırsatları"><s-paragraph color="subdued">Seçim: 100+ gösterim, 3–20 ortalama konum ve %3’ün altında CTR. Bunlar düzenleme için başlangıç filtreleridir. Düşük CTR’nin tek nedeni başlık olmayabilir.</s-paragraph>{g.opportunities.length?<s-table><s-table-header-row><s-table-header>Ürün / koleksiyon</s-table-header><s-table-header>Gösterim</s-table-header><s-table-header>Tıklama</s-table-header><s-table-header>CTR</s-table-header><s-table-header>Ortalama konum</s-table-header><s-table-header>İşlem</s-table-header></s-table-header-row><s-table-body>{g.opportunities.map(o=><s-table-row key={o.pageId}><s-table-cell>{o.pageTitle}</s-table-cell><s-table-cell>{fmt(o.impressions)}</s-table-cell><s-table-cell>{fmt(o.clicks)}</s-table-cell><s-table-cell>{percent(o.ctr)}</s-table-cell><s-table-cell>{o.position?.toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1})}</s-table-cell><s-table-cell><s-stack direction="inline" gap="small"><s-button disabled={busy} onClick={()=>onEdit(o.pageId)}>Metni düzenle</s-button><s-button onClick={()=>{setFocus(o.pageId);document.getElementById('growth-queries')?.scrollIntoView({behavior:'smooth'});}}>Arama ifadelerini göster</s-button></s-stack></s-table-cell></s-table-row>)}</s-table-body></s-table>:<s-paragraph>{g.current?"Bu filtrelere uygun sayfa bulunamadı.":"Google verileri geldikten sonra fırsatlar burada görünecek."}</s-paragraph>}</s-section>
 <div id="growth-queries"><s-section heading="Anahtar kelime → ürün eşleşmesi"><s-paragraph color="subdued">Google’ın gerçekten gösterdiği sorgu–sayfa çiftleridir. İfadenin ürüne uygunluğunu kontrol edip hedef olarak seçin. Aynı ifadenin birden fazla sayfada görünmesi otomatik olarak sorun olduğu anlamına gelmez.</s-paragraph><s-search-field label="ABD arama ifadesi" value={queryFilter} onInput={e=>setQueryFilter(e.currentTarget.value)}/>{focus&&<s-button onClick={()=>setFocus('')}>Tüm ürünlerin ifadelerini göster</s-button>}<s-paragraph color="subdued">İlk {g.queries.length} / {g.queryCount} eşleşen satır. Gizlenen sorgular ve API sınırları nedeniyle bu tam liste değildir.</s-paragraph>{queries.length?<s-table><s-table-header-row><s-table-header>Arama ifadesi</s-table-header><s-table-header>Sayfa</s-table-header><s-table-header>Gösterim / tıklama</s-table-header><s-table-header>Ortalama konum</s-table-header><s-table-header>İşlem</s-table-header></s-table-header-row><s-table-body>{queries.map(q=><s-table-row key={`${q.pageId}-${q.query}`}><s-table-cell>{q.query}{q.pageCount>1&&<s-badge tone="info">{q.pageCount} sayfada yer alıyor</s-badge>}</s-table-cell><s-table-cell>{q.pageTitle}</s-table-cell><s-table-cell>{fmt(q.impressions)} / {fmt(q.clicks)}</s-table-cell><s-table-cell>{q.position?.toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1})||'—'}</s-table-cell><s-table-cell><s-button disabled={busy||q.mapped||q.query.length>150} onClick={()=>onAction({intent:'keyword',pageId:q.pageId,keyword:q.query})}>{q.mapped?"Hedef seçildi":"Hedef olarak seç"}</s-button></s-table-cell></s-table-row>)}</s-table-body></s-table>:<s-paragraph>Bu seçim için sorgu–sayfa verisi yok.</s-paragraph>}</s-section></div>
 <div id="growth-checklist"><s-section heading="Ürünün satın almaya hazır olması"><s-select label="Kontrol edilecek ürün" value={product?.pageId||''} onChange={e=>setFocus(e.currentTarget.value)}>{g.products.map(p=><s-option key={p.pageId} value={p.pageId}>{p.pageTitle}</s-option>)}</s-select>{product?<><s-paragraph color="subdued">Görsel ve açıklamanın varlığı katalogdan kontrol edilir. Kalite ve diğer maddeleri elle kontrol etmeniz gerekir; bunlar otomatik olarak başarılı sayılmaz.</s-paragraph>{product.checks.map(c=><div key={c.key} className="seo-growth-check"><div><s-text>{c.label}</s-text><div><s-text color="subdued">{c.automatic?"Katalog bilgileri":c.updatedAt?`Elle kontrol edildi: ${new Date(c.updatedAt).toLocaleDateString('tr-TR')}`:"Elle kontrol gerekli"}</s-text></div></div>{c.automatic?<s-badge tone={c.status==='yes'?'success':'warning'}>{c.status==='yes'?'Var':'Yoxdur'}</s-badge>:<s-select label={c.label} labelAccessibilityVisibility="exclusive" value={c.status} disabled={busy} onChange={e=>onAction({intent:'growth-check',pageId:product.pageId,check:c.key,status:e.currentTarget.value})}><s-option value="unknown">Kontrol edilmedi</s-option><s-option value="yes">Kontrol ettim, uygun</s-option><s-option value="no">Düzeltme gerekli</s-option></s-select>}</div>)}{product.url&&<s-link href={product.url} target="_blank">Ürünü canlı mağazada kontrol et</s-link>}</>:<s-paragraph>Önce ürün kataloğunu getirin.</s-paragraph>}</s-section></div>
 <div id="growth-outreach"><OutreachEditor data={data} busy={busy} onAction={onAction}/></div>
 <s-section heading="Değişiklik sonrası sonuçlar"><s-paragraph color="subdued">Bu uygulamada kaydedilen SEO düzenlemesinden önceki ve sonraki 7 günlük ABD verileri karşılaştırılır. Değişiklik günü sayılmaz. Mevsim, fiyat, rekabet ve diğer değişiklikler sonucu etkileyebilir.</s-paragraph>{g.effects.length?g.effects.map(e=><div className="seo-growth-effect" key={e.id}><s-heading>{e.pageTitle}</s-heading><s-paragraph>Değişiklik: {e.changed} · Pasifik tarihine göre</s-paragraph>{e.before&&e.after&&<div className="seo-comparison"><div><s-text>Önce: {e.beforeStart} — {e.beforeEnd}</s-text><MetricLine value={e.before}/></div><div><s-text>Sonra: {e.afterStart} — {e.afterEnd}</s-text><MetricLine value={e.after}/><s-paragraph>Tıklama farkı: {fmt(e.clickDifference||0)}</s-paragraph></div></div>}<s-paragraph color="subdued">{e.reason}</s-paragraph></div>):<s-paragraph>Henüz uygun bir canlı SEO değişikliği yok. Onaylanmış düzenleme ve yeterli günlük Google verisi olduğunda karşılaştırma görünecek.</s-paragraph>}</s-section>
 </s-stack>;
}
