import {useState} from 'react';
import type {ActionInput,ActionResult,Dashboard} from '../lib/types';
type Props={data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void;result?:ActionResult};
export function GoogleConnectionView({data,busy,onAction,result}:Props){
 const g=data.google;const [property,setProperty]=useState(g?.property||''),[auto,setAuto]=useState(g?.autoSync||false);
 if(!g)return null;
 return <s-section heading="Google Search Console bağlantısı"><s-stack direction="block" gap="base">
 {!g.configured&&<s-banner tone="info">Google girişi sunucuda etkinleştirilmelidir. Bu sırada CSV içe aktarmayı kullanabilirsiniz.</s-banner>}
 <s-paragraph>{g.connected?"Google hesabı bağlı. Raporlar doğrudan Search Console’dan getirilir.":"Google hesabınıza okuma izni vererek CSV olmadan rapor alın."}</s-paragraph>
 <s-stack direction="inline" gap="base"><s-button disabled={busy||!g.configured||!data.canManageGoogle} onClick={()=>onAction({intent:'google-connect'})}>{g.connected?"Google hesabını yeniden bağla":"Google bağlantısını başlat"}</s-button><s-button disabled={busy} onClick={()=>onAction({intent:'refresh'})}>Bağlantı durumunu yenile</s-button></s-stack>
 {result?.connectURL&&<s-banner tone="info"><s-link href={result.connectURL} target="_blank">Google izin sayfasını aç</s-link><s-paragraph>Yeni pencerede girişi tamamlayın, ardından burada bağlantı durumunu yenileyin. Bağlantı 10 dakika geçerlidir.</s-paragraph></s-banner>}
 {g.connected&&<><s-select label="Search Console mülkü" value={property||g.property} onChange={e=>setProperty(e.currentTarget.value)}>{g.properties.map(p=><s-option key={p} value={p}>{p}</s-option>)}</s-select><s-checkbox label="Her gün otomatik güncelle" checked={auto} onChange={e=>setAuto(e.currentTarget.checked)}/><s-paragraph color="subdued">Otomatik güncelleme için sunucunun günlük görevi çalışmalıdır. Son API güncellemesi: {g.syncedAt?new Date(g.syncedAt).toLocaleString('tr-TR'):"Henüz yok"}. Verilerin tamamlanması için son 3 gün beklenir.</s-paragraph><s-stack direction="inline" gap="base"><s-button disabled={busy||!data.canManageGoogle} onClick={()=>onAction({intent:'google-settings',property:property||g.property,autoSync:String(auto)})}>Ayarları kaydet</s-button><s-button variant="primary" disabled={busy} onClick={()=>onAction({intent:'google-sync'})}>Google raporunu getir</s-button><s-button tone="critical" disabled={busy||!data.canManageGoogle} onClick={()=>onAction({intent:'google-disconnect'})}>Google bağlantısını kaldır</s-button></s-stack></>}
 {!data.canManageGoogle&&<s-paragraph color="subdued">Google hesabını mağaza sahibi veya ayrıca yetkilendirilmiş bir kullanıcı bağlayabilir.</s-paragraph>}
 </s-stack></s-section>;
}
const size=(bytes:number)=>`${(bytes/1024).toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1})} KB`;
export function CompressionView({data,busy,onAction}:Props){
 const [imageId,setImageId]=useState(''),[confirm,setConfirm]=useState(''),[remove,setRemove]=useState('');const images=new Map<string,{id:string;title:string}>();
 for(const p of data.catalog.pages)for(const image of p.images||[])if(image.id)images.set(image.id,{id:image.id,title:p.title});
 return <><s-section heading="Görsel sıkıştırma"><s-stack direction="block" gap="base"><s-paragraph>Boyutlar korunur. JPEG ve WebP, 82 kalite değeriyle yeniden kodlanır; PNG kayıpsız sıkıştırılır. Dosya küçülmezse değişiklik hazırlanmaz. Shopify da görselleri optimize ettiği için mağaza hızının artacağı garanti edilmez.</s-paragraph>{!data.compressionConfigured&&<s-banner tone="info">Görsel önizlemeleri için sunucunun entegrasyon anahtarı ayarlanmalıdır.</s-banner>}<s-select label="Sıkıştırılacak ürün görseli" value={imageId} onChange={e=>setImageId(e.currentTarget.value)}><s-option value="">Görsel seç</s-option>{[...images.values()].map(i=><s-option key={i.id} value={i.id}>{i.title} · {i.id.split('/').pop()}</s-option>)}</s-select><s-button disabled={busy||!imageId||!data.compressionConfigured} onClick={()=>onAction({intent:'compression-prepare',imageId})}>Sıkıştırılmış önizleme hazırla</s-button><s-paragraph color="subdued">En fazla 20 MB ve 40 milyon piksel; animasyonlar desteklenmez. Aynı anda 10 işlem ve bunların orijinalleri saklanır.</s-paragraph></s-stack></s-section>
 {(data.compressions||[]).map(c=><s-section key={c.id} heading={images.get(c.imageId)?.title||"Görsel sıkıştırma"}><s-stack direction="block" gap="base"><s-paragraph>{size(c.beforeBytes)} → {size(c.afterBytes)} · Hazırlanan dosyada {Math.round((1-c.afterBytes/c.beforeBytes)*100)}% azalma. Durum: {({draft:"Onay bekliyor",submitted:"Shopify işlemesine gönderildi",unconfirmed:"Sonucu kontrol etmek gerekiyor",ready:"Shopify’da doğrulandı",failed:"İşlem başarısız"} as Record<string,string>)[c.status]||c.status}</s-paragraph><div className="seo-compression-preview"><div><s-heading>Orijinal</s-heading><img src={c.originalURL} alt="Sıkıştırmadan önceki ürün" loading="lazy"/><s-link href={c.originalURL} target="_blank">Orijinal yedeği aç / indir</s-link></div><div><s-heading>Sıkıştırılmış önizleme</s-heading><img src={c.optimizedURL} alt="Sıkıştırılmış ürün önizlemesi" loading="lazy"/><s-link href={c.optimizedURL} target="_blank">Tam boyutta karşılaştır</s-link></div></div>
 <s-stack direction="inline" gap="base">{c.status==='draft'&&<s-button disabled={busy||!data.canWriteFiles} onClick={()=>setConfirm(c.id)}>Shopify’da uygula</s-button>}{['submitted','unconfirmed','ready'].includes(c.status)&&<s-button disabled={busy} onClick={()=>onAction({intent:'compression-check',id:c.id})}>İşlem durumunu kontrol et</s-button>}{!['submitted','unconfirmed'].includes(c.status)&&<s-button disabled={busy} tone="critical" onClick={()=>setRemove(c.id)}>İşlemi ve yedeği sil</s-button>}</s-stack>
 {confirm===c.id&&<s-banner tone="warning"><s-paragraph>Bu dosyanın kullanıldığı tüm yerlerde görsel değişecek. Her iki görseli tam boyutta karşılaştırın. Orijinal burada saklanacak.</s-paragraph><s-button disabled={busy} variant="primary" onClick={()=>{onAction({intent:'compression-apply',id:c.id,afterHash:c.afterHash,confirm:'APPLY'});setConfirm('');}}>Onayla ve dosyayı güncelle</s-button></s-banner>}
 {remove===c.id&&<s-banner tone="warning"><s-paragraph>Orijinal yedek de silinecek. Gerekiyorsa önce indirin. Bu işlem Shopify dosyasını değiştirmez.</s-paragraph><s-button tone="critical" disabled={busy} onClick={()=>{onAction({intent:'compression-delete',id:c.id,confirm:'DELETE'});setRemove('');}}>Silmeyi onayla</s-button></s-banner>}
 </s-stack></s-section>)}</>;
}
export function BacklinksView({data,busy,onAction}:Props){const [url,setURL]=useState('');
 return <><s-section heading="Backlink fırsatları ve takibi"><s-stack direction="block" gap="base"><s-paragraph>Harici sitedeki kaynak sayfasını ekleyin. Araç, No Sweat USA bağlantısını, bağlantı özelliklerini ve bağlantısız marka anılmalarını kontrol eder. Harici sitede kendiliğinden hesap veya bağlantı oluşturmaz.</s-paragraph><s-url-field label="Harici kaynak sayfası" value={url} onInput={e=>setURL(e.currentTarget.value)} placeholder="https://example.com/article"/><s-stack direction="inline" gap="base"><s-button disabled={busy||!url} onClick={()=>onAction({intent:'backlink-add',url})}>Takibe ekle</s-button><s-button disabled={busy||!data.backlinks?.length} onClick={()=>onAction({intent:'backlink-check'})}>Kaynakları kontrol et</s-button></s-stack><s-checkbox label="Her gün otomatik kontrol et (sunucu görevi gerekir)" checked={data.backlinksAuto||false} disabled={busy} onChange={e=>onAction({intent:'backlink-auto',enabled:String(e.currentTarget.checked)})}/></s-stack></s-section>
 <s-section heading="Fırsat ara"><s-paragraph color="subdued">Bu sorgular arama için hazırlanmıştır; sonuçlar otomatik alınmaz. Uygun bir yazı bulduğunuzda URL’sini takibe ekleyin.</s-paragraph><s-stack direction="block" gap="base">{(data.opportunities||[]).map(o=><s-link key={o.query} href={o.url} target="_blank">{o.query}</s-link>)}</s-stack></s-section>
 {(data.backlinks||[]).map(b=><s-section key={b.id} heading={new URL(b.url).hostname}><s-link href={b.url} target="_blank">{b.url}</s-link><s-paragraph>{({unchecked:"Kontrol edilmedi",found:"Mağazaya bağlantı bulundu",mention:"Marka adı var, bağlantı bulunamadı",missing:"HTML içinde bağlantı bulunamadı",unknown:"Sonuç bilinmiyor"} as Record<string,string>)[b.status]} · {b.checkedAt?new Date(b.checkedAt).toLocaleString('tr-TR'):''}</s-paragraph>{b.links.map((l,i)=><s-paragraph key={i}>{l.anchor||"(metinsiz bağlantı)"} → {l.url} · rel: {l.rel||"nofollow/sponsored belirtilmemiş"}</s-paragraph>)}<s-paragraph color="subdued">{b.note}</s-paragraph><s-button disabled={busy} onClick={()=>onAction({intent:'backlink-delete',id:b.id})}>Listeden kaldır</s-button></s-section>)}</>;
}
