import { useState } from 'react';
import type { ActionInput, Dashboard, Image, ImageDraft } from '../lib/types';
type Props = {data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void};
export function TechnicalView({data,busy,onAction}:Props){
  const report=data.technical;
  return <><s-section heading="Texniki SEO və qırıq linklər"><s-stack direction="block" gap="base"><s-paragraph>Mağazanın yayımlanmış səhifələrində status, canonical, noindex, H1 və JSON-LD yoxlanır. Daxili linklərdə 404/410 səhifələri axtarılır.</s-paragraph><s-button variant="primary" loading={busy} disabled={busy||!data.catalog.pages.length} onClick={()=>onAction({intent:'technical'})}>Texniki yoxlamanı başlat</s-button><s-paragraph color="subdued">Hər yoxlama maksimum 30 səhifə və 60 unikal daxili linki əhatə edir. Bu, server HTML yoxlamasıdır; JavaScript render, rich-result uyğunluğu və Google indekslənməsi yoxlanmır.</s-paragraph></s-stack></s-section>
  {report&&<><s-section heading="Səhifə və schema yoxlaması"><s-paragraph color="subdued">Son yoxlama: {new Date(report.checkedAt).toLocaleString('az-AZ')}</s-paragraph><s-table><s-table-header-row><s-table-header>Səhifə</s-table-header><s-table-header>HTTP</s-table-header><s-table-header>H1</s-table-header><s-table-header>Canonical</s-table-header><s-table-header>İndeks göstərişi</s-table-header><s-table-header>JSON-LD</s-table-header></s-table-header-row><s-table-body>{report.pages.map(p=><s-table-row key={p.pageId}><s-table-cell><s-link href={p.url} target="_blank">{p.title}</s-link>{p.error&&<p>{p.error}</p>}</s-table-cell><s-table-cell>{p.status??'Yoxlanmadı'}</s-table-cell><s-table-cell>{p.technical?.h1Count??'—'}</s-table-cell><s-table-cell>{p.technical?(p.technical.canonical?'Var':'Tapılmadı'):'—'}</s-table-cell><s-table-cell>{p.technical?(p.technical.noindex?<s-badge tone="warning">noindex</s-badge>:'Meta noindex yoxdur'):'—'}</s-table-cell><s-table-cell>{p.technical?.schemaTypes.join(', ')||'Tapılmadı'}{p.technical?.invalidSchema?<s-badge tone="critical">Sintaksis xətası</s-badge>:null}</s-table-cell></s-table-row>)}</s-table-body></s-table><s-paragraph color="subdued">H1 sayında gizli elementlər də ola bilər. JSON-LD-nin mövcudluğu təkbaşına düzgünlüyünü təsdiqləmir. X-Robots-Tag başlığı bu yoxlamaya daxil deyil.</s-paragraph></s-section>
  <s-section heading={`Daxili linklər · ${report.links.filter(l=>l.broken).length} qırıq link`}><s-table><s-table-header-row><s-table-header>URL</s-table-header><s-table-header>Status</s-table-header><s-table-header>Mənbə səhifələr</s-table-header></s-table-header-row><s-table-body>{report.links.map(l=><s-table-row key={l.url}><s-table-cell><s-link href={l.url} target="_blank">{l.url}</s-link></s-table-cell><s-table-cell><s-badge tone={l.broken?'critical':l.status===200?'success':'warning'}>{l.status??'Yoxlanmadı'}</s-badge>{l.error&&<p>{l.error}</p>}</s-table-cell><s-table-cell>{l.sources.join(', ')}</s-table-cell></s-table-row>)}</s-table-body></s-table><s-paragraph color="subdued">403/429 və şəbəkə xətaları qırıq link kimi sayılmır. Yönləndirmələr yalnız mağazanın təhlükəsiz daxili yollarında izlənir.</s-paragraph></s-section>
  <s-section heading="Robots və sitemap"><s-stack direction="inline" gap="base">{report.infrastructure.map(i=><s-badge key={i.name} tone={i.valid?'success':'warning'}>{i.name}: {i.valid?'Əlçatandır':i.status??'Yoxlanmadı'}</s-badge>)}</s-stack><s-paragraph color="subdued">Əlçatan olması Google-a təqdim edildiyini və ya indeksləndiyini göstərmir.</s-paragraph></s-section>{report.warnings.map(w=><s-banner key={w} tone="warning">{w}</s-banner>)}</>}
  </>;
}
function ImageEditor({image,draft,pageTitle,busy,canWrite,onAction}:{image:Image;draft?:ImageDraft;pageTitle:string;busy:boolean;canWrite:boolean;onAction:Props['onAction']}){
  const [alt,setAlt]=useState(draft?.after??image.altText),[confirm,setConfirm]=useState(false);
  return <div className="seo-image-row"><img src={image.url} alt={image.altText||'Redaktə ediləcək məhsul şəkli'} loading="lazy"/><div><s-heading>{pageTitle}</s-heading><s-text-area label="Şəkildə görünəni dəqiq təsvir et" value={alt} rows={3} maxLength={512} onInput={e=>{setAlt(e.currentTarget.value);setConfirm(false);}} details="Dekorativ şəkil üçün boş alt uyğun ola bilər. Məhsulun faydası haqqında şəkildən görünməyən iddia yazma."/><div className="seo-image-actions"><s-button disabled={busy} onClick={()=>onAction({intent:'image-draft',imageId:image.id!,alt})}>Layihəni saxla</s-button>{draft&&<><s-button disabled={busy||!canWrite||alt!==draft.after} onClick={()=>setConfirm(true)}>Shopify-da tətbiq et</s-button><s-button disabled={busy} tone="critical" onClick={()=>onAction({intent:'image-delete',imageId:image.id!})}>Layihəni sil</s-button></>}</div>{draft&&<div className="seo-image-before"><strong>Əvvəl:</strong> {draft.before||'(boş)'}<br/><strong>Layihə:</strong> {draft.after||'(boş)'}</div>}{confirm&&draft&&<s-banner tone="warning"><s-paragraph>Yuxarıdakı alt mətn Shopify faylında dəyişəcək. Eyni fayl başqa səhifələrdə də istifadə olunursa, dəyişiklik orada da görünəcək.</s-paragraph><s-button disabled={busy||alt!==draft.after} variant="primary" onClick={()=>{onAction({intent:'image-apply',imageId:image.id!,alt:draft.after,confirm:'APPLY'});setConfirm(false);}}>Təsdiqlə və tətbiq et</s-button></s-banner>}</div></div>;
}
export function ImagesView({data,busy,onAction}:Props){
  const [onlyMissing,setOnlyMissing]=useState(false);const images=new Map<string,{image:Image;pageTitle:string}>();
  for(const page of data.catalog.pages)for(const image of page.images||[])if(image.id&&!images.has(image.id))images.set(image.id,{image,pageTitle:page.title});
  const rows=[...images.values()].filter(({image})=>!onlyMissing||!image.altText);
  return <s-section heading="Şəkillərin SEO və əlçatanlıq mətnləri"><s-stack direction="block" gap="base"><s-paragraph>Alt mətnləri şəkli görərək redaktə et. Şəkillərin faylı, ölçüsü və keyfiyyəti dəyişdirilmir.</s-paragraph>{!data.canWriteFiles&&<s-banner tone="info">Şəkil alt mətnini canlı dəyişmək üçün tətbiqə write_files icazəsi lazımdır.</s-banner>}<s-checkbox label="Yalnız alt mətni boş olanlar" checked={onlyMissing} onChange={e=>setOnlyMissing(e.currentTarget.checked)}/>{data.catalog.pages.some(p=>p.imagesTruncated)&&<s-banner tone="warning">Bəzi məhsullarda ilk 100 media faylı gətirilib. Tam şəkil siyahısı yoxlanmayıb.</s-banner>}{rows.length?rows.map(({image,pageTitle})=><ImageEditor key={image.id} image={image} draft={data.imageDrafts.find(d=>d.imageId===image.id)} pageTitle={pageTitle} busy={busy} canWrite={data.canWriteFiles} onAction={onAction}/>):<s-paragraph>Bu filtrə uyğun məhsul şəkli yoxdur.</s-paragraph>}</s-stack></s-section>;
}
