import { useState } from 'react';
import type { ActionInput, Dashboard, Image, ImageDraft } from '../lib/types';
type Props = {data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void};
export function TechnicalView({data,busy,onAction}:Props){
  const report=data.technical;
  return <><s-section heading="Teknik SEO ve kırık bağlantılar"><s-stack direction="block" gap="base"><s-paragraph>Mağazanın yayınlanmış sayfalarında durum, canonical, noindex, H1 ve JSON-LD kontrol edilir. Dahili bağlantılarda 404/410 sayfaları aranır.</s-paragraph><s-button variant="primary" loading={busy} disabled={busy||!data.catalog.pages.length} onClick={()=>onAction({intent:'technical'})}>Teknik kontrolü başlat</s-button><s-paragraph color="subdued">Her kontrol en fazla 30 sayfayı ve 60 benzersiz dahili bağlantıyı kapsar. Bu bir sunucu HTML kontrolüdür; JavaScript oluşturma, zengin sonuç uyumluluğu ve Google dizine ekleme durumu kontrol edilmez.</s-paragraph></s-stack></s-section>
  {report&&<><s-section heading="Sayfa ve şema kontrolü"><s-paragraph color="subdued">Son kontrol: {new Date(report.checkedAt).toLocaleString('tr-TR')}</s-paragraph><s-table><s-table-header-row><s-table-header>Sayfa</s-table-header><s-table-header>HTTP</s-table-header><s-table-header>H1</s-table-header><s-table-header>Canonical</s-table-header><s-table-header>Dizin yönergesi</s-table-header><s-table-header>JSON-LD</s-table-header></s-table-header-row><s-table-body>{report.pages.map(p=><s-table-row key={p.pageId}><s-table-cell><s-link href={p.url} target="_blank">{p.title}</s-link>{p.error&&<p>{p.error}</p>}</s-table-cell><s-table-cell>{p.status??"Kontrol edilmedi"}</s-table-cell><s-table-cell>{p.technical?.h1Count??'—'}</s-table-cell><s-table-cell>{p.technical?(p.technical.canonical?'Var':"Bulunamadı"):'—'}</s-table-cell><s-table-cell>{p.technical?(p.technical.noindex?<s-badge tone="warning">noindex</s-badge>:"Meta noindex yok"):'—'}</s-table-cell><s-table-cell>{p.technical?.schemaTypes.join(', ')||"Bulunamadı"}{p.technical?.invalidSchema?<s-badge tone="critical">Sözdizimi hatası</s-badge>:null}</s-table-cell></s-table-row>)}</s-table-body></s-table><s-paragraph color="subdued">H1 sayısına gizli öğeler de dahil olabilir. JSON-LD’nin varlığı tek başına doğruluğunu kanıtlamaz. X-Robots-Tag başlığı bu kontrole dahil değildir.</s-paragraph></s-section>
  <s-section heading={`Dahili bağlantılar · ${report.links.filter(l=>l.broken).length} kırık bağlantı`}><s-table><s-table-header-row><s-table-header>URL</s-table-header><s-table-header>Durum</s-table-header><s-table-header>Kaynak sayfalar</s-table-header></s-table-header-row><s-table-body>{report.links.map(l=><s-table-row key={l.url}><s-table-cell><s-link href={l.url} target="_blank">{l.url}</s-link></s-table-cell><s-table-cell><s-badge tone={l.broken?'critical':l.status===200?'success':'warning'}>{l.status??"Kontrol edilmedi"}</s-badge>{l.error&&<p>{l.error}</p>}</s-table-cell><s-table-cell>{l.sources.join(', ')}</s-table-cell></s-table-row>)}</s-table-body></s-table><s-paragraph color="subdued">403/429 ve ağ hataları kırık bağlantı sayılmaz. Yönlendirmeler yalnızca mağazanın güvenli dahili yollarında takip edilir.</s-paragraph></s-section>
  <s-section heading="Robots ve site haritası"><s-stack direction="inline" gap="base">{report.infrastructure.map(i=><s-badge key={i.name} tone={i.valid?'success':'warning'}>{i.name}: {i.valid?"Erişilebilir":i.status??"Kontrol edilmedi"}</s-badge>)}</s-stack><s-paragraph color="subdued">Erişilebilir olması, Google’a gönderildiği veya dizine eklendiği anlamına gelmez.</s-paragraph></s-section>{report.warnings.map(w=><s-banner key={w} tone="warning">{w}</s-banner>)}</>}
  </>;
}
function ImageEditor({image,draft,pageTitle,busy,canWrite,onAction}:{image:Image;draft?:ImageDraft;pageTitle:string;busy:boolean;canWrite:boolean;onAction:Props['onAction']}){
  const [alt,setAlt]=useState(draft?.after??image.altText),[confirm,setConfirm]=useState(false);
  return <div className="seo-image-row"><img src={image.url} alt={image.altText||"Düzenlenecek ürün görseli"} loading="lazy"/><div><s-heading>{pageTitle}</s-heading><s-text-area label="Görselde görünenleri doğru şekilde açıklayın" value={alt} rows={3} maxLength={512} onInput={e=>{setAlt(e.currentTarget.value);setConfirm(false);}} details="Dekoratif görseller için boş alt metin uygun olabilir. Ürünün faydaları hakkında görselde görülmeyen iddialar yazmayın."/><div className="seo-image-actions"><s-button disabled={busy} onClick={()=>onAction({intent:'image-draft',imageId:image.id!,alt})}>Taslağı kaydet</s-button>{draft&&<><s-button disabled={busy||!canWrite||alt!==draft.after} onClick={()=>setConfirm(true)}>Shopify’da uygula</s-button><s-button disabled={busy} tone="critical" onClick={()=>onAction({intent:'image-delete',imageId:image.id!})}>Taslağı sil</s-button></>}</div>{draft&&<div className="seo-image-before"><strong>Önce:</strong> {draft.before||"(boş)"}<br/><strong>Taslak:</strong> {draft.after||"(boş)"}</div>}{confirm&&draft&&<s-banner tone="warning"><s-paragraph>Yukarıdaki alt metin Shopify dosyasında değişecek. Aynı dosya başka sayfalarda da kullanılıyorsa değişiklik oralarda da görünecek.</s-paragraph><s-button disabled={busy||alt!==draft.after} variant="primary" onClick={()=>{onAction({intent:'image-apply',imageId:image.id!,alt:draft.after,confirm:'APPLY'});setConfirm(false);}}>Onayla ve uygula</s-button></s-banner>}</div></div>;
}
export function ImagesView({data,busy,onAction}:Props){
  const [onlyMissing,setOnlyMissing]=useState(false);const images=new Map<string,{image:Image;pageTitle:string}>();
  for(const page of data.catalog.pages)for(const image of page.images||[])if(image.id&&!images.has(image.id))images.set(image.id,{image,pageTitle:page.title});
  const rows=[...images.values()].filter(({image})=>!onlyMissing||!image.altText);
  return <s-section heading="Görsellerin SEO ve erişilebilirlik metinleri"><s-stack direction="block" gap="base"><s-paragraph>Alt metinleri görseli inceleyerek düzenleyin. Görsel dosyaları, boyutları ve kalitesi değiştirilmez.</s-paragraph>{!data.canWriteFiles&&<s-banner tone="info">Görsel alt metnini canlı olarak değiştirmek için uygulamanın write_files izni gerekir.</s-banner>}<s-checkbox label="Yalnızca alt metni boş olanlar" checked={onlyMissing} onChange={e=>setOnlyMissing(e.currentTarget.checked)}/>{data.catalog.pages.some(p=>p.imagesTruncated)&&<s-banner tone="warning">Bazı ürünlerde ilk 100 medya dosyası getirildi. Görsellerin tamamı kontrol edilmedi.</s-banner>}{rows.length?rows.map(({image,pageTitle})=><ImageEditor key={image.id} image={image} draft={data.imageDrafts.find(d=>d.imageId===image.id)} pageTitle={pageTitle} busy={busy} canWrite={data.canWriteFiles} onAction={onAction}/>):<s-paragraph>Bu filtreye uygun ürün görseli yok.</s-paragraph>}</s-stack></s-section>;
}
