import { useEffect, useState } from 'react';
import type { ActionInput, ActionResult, Dashboard, Draft, Page, SEO } from '../lib/types';
import './seo.css';
import GrowthPanel from './GrowthPanel';
import {GoogleConnectionView,CompressionView,BacklinksView} from './Integrations';
import { ImagesView, TechnicalView } from './PremiumFeatures';

type Props = {data:Dashboard;busy:boolean;result?:ActionResult;onAction:(input:ActionInput)=>void};
const tabs = ['ABŞ müştəriləri','Ümumi baxış','Səhifələr','Açar sözlər','Daxili linklər','Şəkillər','Şəkil sıxılması','Backlinklər','Texniki SEO','Google nəticələri','Layihələr','Tarixçə'] as const;
type Tab = typeof tabs[number];
const number = (n:number) => new Intl.NumberFormat('az-AZ').format(n);
const date = (s:string|null) => s?new Date(s).toLocaleString('az-AZ',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Hələ yoxlanmayıb';
const priority = {high:'Yüksək',medium:'Orta',low:'Nəzərdən keçir'};
function TextPair({before,after}:{before:SEO;after:SEO}) {return <div className="seo-comparison"><div><s-text color="subdued">ƏVVƏL</s-text><h3>{before.title||'Xüsusi başlıq yoxdur'}</h3><p>{before.description||'Xüsusi meta təsvir yoxdur'}</p></div><div className="seo-after"><s-text color="subdued">TƏKLİF EDİLƏN</s-text><h3>{after.title}</h3><p>{after.description||'Təsvir boşdur'}</p></div></div>;}
function Empty({heading,text}:{heading:string;text:string}){return <div className="seo-empty"><s-icon type="search"/><s-heading>{heading}</s-heading><s-paragraph color="subdued">{text}</s-paragraph></div>;}
function Editor({page,draft,busy,onAction,onClose}:{page:Page;draft?:Draft;busy:boolean;onAction:Props['onAction'];onClose:()=>void}){
  const [title,setTitle]=useState(draft?.after.title||page.seo.title||page.title);
  const [description,setDescription]=useState(draft?.after.description||page.seo.description||'');
  const invalid=!title.trim()||title.length>70||description.length>320;
  return <s-section heading={page.title}><div className="seo-editor"><div><s-stack gap="base" direction="block">
    <s-text-field label="SEO başlığı" value={title} maxLength={70} onInput={e=>setTitle(e.currentTarget.value)} details={`${title.length} / 70 simvol`} required/>
    <s-text-area label="Meta təsvir" value={description} rows={5} maxLength={320} onInput={e=>setDescription(e.currentTarget.value)} details={`${description.length} / 320 simvol. Təxminən 155 simvol redaktə bələdçisidir.`}/>
    <s-button disabled={busy} onClick={()=>{setTitle(page.suggestion.title);setDescription(page.suggestion.description);}}>Mənbə mətnindən təklif hazırla</s-button>
    <s-paragraph color="subdued">{page.suggestion.note}</s-paragraph>{page.keyword&&<s-paragraph>Seçilmiş hədəf ifadə: <strong>{page.keyword}</strong>. Yalnız məhsula uyğundursa mətndə təbii istifadə et.</s-paragraph>}
  </s-stack></div><div className="seo-preview"><s-heading>Google önizləməsi</s-heading><div className="seo-snippet"><small>{page.url||'Səhifə onlayn mağazada yayımlanmayıb'}</small><h3>{title}</h3><p>{description||'Meta təsvir burada görünəcək.'}</p></div><s-paragraph color="subdued">Təxmini görünüşdür. Google sorğuya uyğun başqa mətn göstərə bilər.</s-paragraph></div></div>
  <s-stack gap="base" direction="inline"><s-button variant="primary" disabled={busy||invalid||draft?.stale} onClick={()=>onAction({intent:'save-draft',pageId:page.id,title,description})}>Layihəni saxla</s-button><s-button disabled={busy} onClick={onClose}>Bağla</s-button>{page.url&&<s-link href={page.url} target="_blank">Canlı səhifəni aç</s-link>}</s-stack>
  {draft?.stale&&<s-banner tone="warning">Bu layihənin mənbə məlumatı dəyişib. Layihələr bölməsində köhnə layihəni silib yenisini hazırla.</s-banner>}
  <div className="seo-findings">{page.issues.map(i=><div className="seo-finding" key={i.code}><s-badge tone={i.severity==='high'?'critical':i.severity==='medium'?'warning':'info'}>{priority[i.severity]}</s-badge><div><strong>{i.label}</strong><p>{i.detail}</p></div></div>)}</div></s-section>;
}
function KeywordRow({page,busy,mapping,onAction,duplicate}:{page:Page;busy:boolean;mapping:string;onAction:Props['onAction'];duplicate:boolean}){
  const [keyword,setKeyword]=useState(mapping);
  return <s-table-row><s-table-cell>{page.title}</s-table-cell><s-table-cell><div className="seo-keyword"><s-text-field label="Hədəf ifadə" labelAccessibilityVisibility="exclusive" value={keyword} maxLength={150} onInput={e=>setKeyword(e.currentTarget.value)}/><s-button disabled={busy} onClick={()=>onAction({intent:'keyword',pageId:page.id,keyword})}>Saxla</s-button></div></s-table-cell><s-table-cell>{duplicate?<s-badge tone="warning">Bir neçə səhifədədir</s-badge>:mapping?<s-badge>Təyin edilib</s-badge>:<s-text color="subdued">Təyin edilməyib</s-text>}</s-table-cell></s-table-row>;
}
function GoogleImport({onAction,busy}:{onAction:Props['onAction'];busy:boolean}){
  const [start,setStart]=useState(''),[end,setEnd]=useState(''),[property,setProperty]=useState('sc-domain:nosweatusa.com'),[csv,setCsv]=useState(''),[error,setError]=useState('');
  return <s-section heading="Search Console CSV əlavə et"><s-stack direction="block" gap="base"><s-paragraph>Search Console → Performance → Search results → Export. ZIP-i aç, ingiliscə Pages.csv və ya Queries.csv faylını seç.</s-paragraph><div className="seo-form-grid"><s-date-field label="Başlanğıc tarixi" value={start} onChange={e=>setStart(e.currentTarget.value)}/><s-date-field label="Bitmə tarixi" value={end} onChange={e=>setEnd(e.currentTarget.value)}/></div><s-text-field label="Property" value={property} onInput={e=>setProperty(e.currentTarget.value)}/><label className="seo-file-label">CSV faylı (maksimum 2 MB)<input aria-label="Search Console CSV faylı" type="file" accept=".csv,text/csv" onChange={async e=>{const file=(e.currentTarget as HTMLInputElement).files?.[0];setError('');setCsv('');if(!file)return;if(file.size>2_000_000){setError('Fayl 2 MB-dan böyükdür.');return;}setCsv(await file.text());}}/></label>{error&&<s-banner tone="critical">{error}</s-banner>}<s-button variant="primary" disabled={busy||!csv||!start||!end||!property} onClick={()=>onAction({intent:'gsc-import',csv,startDate:start,endDate:end,property})}>İdxal et</s-button><s-paragraph color="subdued">Tarixləri və ölkə/cihaz/search type filtrlərini ixracla eyni saxla. Google hesabını yuxarıdakı bölmədən qoşaraq CSV-siz hesabat da gətirə bilərsən.</s-paragraph></s-stack></s-section>;
}
export default function SeoDashboard({data,busy,result,onAction}:Props){
  const [tab,setTab]=useState<Tab>('ABŞ müştəriləri'),[search,setSearch]=useState(''),[kind,setKind]=useState('all'),[selected,setSelected]=useState<string|null>(null),[confirm,setConfirm]=useState<Draft|null>(null),[copied,setCopied]=useState(''),[bulk,setBulk]=useState<Draft[]>([]);
  useEffect(()=>{if(result?.ok){setConfirm(null);setBulk([]);if(result.message?.startsWith('Layihə saxlanıldı')){setSelected(null);setTab('Layihələr');}}},[result]);
  const pages=data.catalog.pages,issues=pages.flatMap(p=>p.issues.map(i=>({...i,page:p}))),score=pages.length?Math.round(pages.reduce((n,p)=>n+p.score,0)/pages.length):null;
  const current=pages.find(p=>p.id===selected);
  const filtered=pages.filter(p=>(kind==='all'||p.type===kind)&&`${p.title} ${p.handle}`.toLowerCase().includes(search.toLowerCase()));
  const keywordCounts=Object.values(data.mappings).reduce<Record<string,number>>((a,k)=>{if(k.trim())a[k.toLowerCase()]=(a[k.toLowerCase()]||0)+1;return a;},{});
  const pageTable=(items:Page[]) => <s-table><s-table-header-row><s-table-header listSlot="primary">Səhifə</s-table-header><s-table-header>Növ</s-table-header><s-table-header>Yoxlama balı</s-table-header><s-table-header>Tapıntılar</s-table-header><s-table-header>Əməliyyat</s-table-header></s-table-header-row><s-table-body>{items.map(p=><s-table-row key={p.id}><s-table-cell><strong>{p.title}</strong><div className="seo-url">/{p.type==='product'?'products':'collections'}/{p.handle}</div></s-table-cell><s-table-cell><s-badge>{p.type==='product'?'Məhsul':'Kolleksiya'}</s-badge></s-table-cell><s-table-cell>{p.score}/100</s-table-cell><s-table-cell>{p.issues.length?<s-badge tone={p.issues.some(i=>i.severity==='high')?'critical':'warning'}>{p.issues.length} tapıntı</s-badge>:<s-badge tone="success">Keçib</s-badge>}</s-table-cell><s-table-cell><s-button disabled={busy} onClick={()=>setSelected(p.id)}>İncələ</s-button></s-table-cell></s-table-row>)}</s-table-body></s-table>;
  const topIssues=[...issues].sort((a,b)=>({high:0,medium:1,low:2}[a.severity]-{high:0,medium:1,low:2}[b.severity])).slice(0,5);
  return <s-page heading="No Sweat SEO Studio" inlineSize="large">
    <s-button slot="primary-action" variant="primary" loading={busy} disabled={busy} onClick={()=>onAction({intent:'sync'})}>Kataloqu yoxla</s-button>
    <s-button slot="secondary-actions" disabled={busy||!pages.length} onClick={()=>onAction({intent:'export'})}>Audit CSV</s-button>
    <s-stack direction="block" gap="base">
      <div className="seo-intro"><div><span className="seo-eyebrow">NO SWEAT USA · SHOPIFY SEO</span><h2>Aydın prioritetlər. Daha yaxşı məhsul səhifələri.</h2><p>Son yenilənmə: {date(data.catalog.syncedAt)}</p></div><s-badge tone="success">Shopify daxilində</s-badge></div>
      {result?.error&&<s-banner tone="critical" heading="Əməliyyat alınmadı">{result.error}</s-banner>}
      {result?.message&&<s-banner tone="success">{result.message}</s-banner>}
      {!data.canWrite&&<s-banner tone="info">Oxuma rejimi. Canlı tətbiq üçün mağaza sahibinin tətbiqə write_products icazəsi verməsi lazımdır.</s-banner>}
      <nav className="seo-tabs" aria-label="SEO bölmələri">{tabs.map(t=><s-button key={t} variant={tab===t?'primary':'secondary'} onClick={()=>{setTab(t);setSelected(null);setConfirm(null);setBulk([]);}}>{t}{t==='Layihələr'&&data.drafts.length?` (${data.drafts.length})`:''}</s-button>)}</nav>
      {current?<Editor key={current.id} page={current} draft={data.drafts.find(d=>d.pageId===current.id)} busy={busy} onAction={onAction} onClose={()=>setSelected(null)}/>:<>
      {tab==='ABŞ müştəriləri'&&<GrowthPanel data={data} busy={busy} onAction={onAction} onEdit={setSelected} onNavigate={section=>{if((tabs as readonly string[]).includes(section))setTab(section as Tab);}}/>}
      {tab==='Ümumi baxış'&&<>
        <div className="seo-metrics">{[['SEO yoxlama balı',score===null?'—':`${score}/100`,'Daxili checklist, Google balı deyil'],['Səhifələr',String(pages.length),`${pages.filter(p=>p.type==='product').length} məhsul · ${pages.filter(p=>p.type==='collection').length} kolleksiya`],['Tapıntılar',String(issues.length),`${issues.filter(i=>i.severity==='high').length} yüksək prioritetli`],['Layihələr',String(data.drafts.length),'Nəzərdən keçirməyi gözləyir']].map(([label,value,note])=><s-section key={label}><div className="seo-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div></s-section>)}</div>
        {!pages.length?<s-section><Empty heading="İlk SEO yoxlamanı başlat" text="Kataloqu yoxla düyməsi No Sweat USA məhsullarını və kolleksiyalarını Shopify-dan gətirəcək. Canlı məlumatlar dəyişmir."/></s-section>:<>
          <s-section heading="Əvvəlcə bunları yoxla">{topIssues.length?topIssues.map((i,n)=><div className="seo-priority" key={`${i.page.id}-${i.code}`}><span className="seo-index">0{n+1}</span><div><strong>{i.label}</strong><p>{i.page.title}</p></div><s-badge tone={i.severity==='high'?'critical':i.severity==='medium'?'warning':'info'}>{priority[i.severity]}</s-badge><s-button disabled={busy} onClick={()=>setSelected(i.page.id)}>İncələ</s-button></div>):<Empty heading="Yoxlanmış qaydalarda tapıntı yoxdur" text="Bu nəticə bütün SEO-nun mükəmməl olduğunu göstərmir. İndekslənmə və Google trafikini də izləmək lazımdır."/>}</s-section>
          <s-section heading="Səhifələrin vəziyyəti">{pageTable([...pages].sort((a,b)=>a.score-b.score).slice(0,6))}</s-section>
        </>}
      </>}
      {tab==='Səhifələr'&&<s-section heading="Məhsul və kolleksiyalar"><div className="seo-filters"><s-search-field label="Səhifə axtar" value={search} placeholder="Məhsul adı və ya handle" onInput={e=>setSearch(e.currentTarget.value)}/><s-select label="Səhifə növü" value={kind} onChange={e=>setKind(e.currentTarget.value)}><s-option value="all">Hamısı</s-option><s-option value="product">Məhsullar</s-option><s-option value="collection">Kolleksiyalar</s-option></s-select></div><s-button disabled={busy||!filtered.length||filtered.length>100} onClick={()=>onAction({intent:'bulk-draft',pageIds:JSON.stringify(filtered.map(p=>p.id))})}>Bu siyahı üçün toplu SEO layihəsi hazırla</s-button>{filtered.length?pageTable(filtered):<Empty heading="Səhifə tapılmadı" text="Kataloqu gətir və ya axtarış filtrini dəyiş."/>}</s-section>}
      {tab==='Açar sözlər'&&<s-section heading="Açar söz xəritəsi"><s-paragraph color="subdued">Hər səhifəyə məhsula uyğun bir əsas ifadə təyin et. Təkrar hədəf xəbərdarlığı avtomatik olaraq rəqabət problemi sübut etmir. Axtarış həcmi bu alətdə hesablanmır.</s-paragraph><s-table><s-table-header-row><s-table-header>Səhifə</s-table-header><s-table-header>Hədəf ifadə</s-table-header><s-table-header>Vəziyyət</s-table-header></s-table-header-row><s-table-body>{pages.map(p=><KeywordRow key={p.id} page={p} busy={busy} mapping={data.mappings[p.id]||''} duplicate={keywordCounts[(data.mappings[p.id]||'').toLowerCase()]>1} onAction={onAction}/>)}</s-table-body></s-table></s-section>}
      {tab==='Daxili linklər'&&<s-section heading="Daxili link təklifləri"><s-paragraph color="subdued">Başlıq və teqlərdəki ortaq sözlərə əsaslanır. HTML-i yalnız əlaqəsi faydalı olan mətnə əlavə et. Linklər avtomatik yerləşdirilmir.</s-paragraph>{copied&&<s-banner tone="info">{copied}</s-banner>}{data.links.length?data.links.map(l=><div className="seo-link-row" key={`${l.fromId}-${l.toId}`}><div><small>BU SƏHİFƏDƏN</small><strong>{l.fromTitle}</strong></div><span>→</span><div><small>BU SƏHİFƏYƏ</small><strong>{l.toTitle}</strong><p>Ortaq sözlər: {l.common.join(', ')}</p></div><s-button onClick={async()=>{const html=`<a href="${l.toUrl.replaceAll('&','&amp;').replaceAll('"','&quot;')}">${l.anchor.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}</a>`;try{await navigator.clipboard.writeText(html);setCopied('Linkin HTML-i kopyalandı.');}catch{setCopied(html);}}}>HTML-i kopyala</s-button></div>):<Empty heading="Uyğun link təklifi yoxdur" text="Əlaqəli səhifələr gətirildikcə başlıq və teqlər üzrə təkliflər burada görünəcək."/>}</s-section>}
      {tab==='Şəkillər'&&<ImagesView data={data} busy={busy} onAction={onAction}/>}
      {tab==='Texniki SEO'&&<TechnicalView data={data} busy={busy} onAction={onAction}/>}
      {tab==='Şəkil sıxılması'&&<CompressionView data={data} busy={busy} onAction={onAction}/>}
      {tab==='Backlinklər'&&<BacklinksView data={data} busy={busy} onAction={onAction}/>}
      {tab==='Google nəticələri'&&<>
        <GoogleConnectionView key={String(data.google?.connected)+data.google?.property} data={data} busy={busy} onAction={onAction} result={result}/>
        {data.gsc?<><div className="seo-metrics">{[['Klik',number(data.gsc.totals.clicks)],['Görünmə',number(data.gsc.totals.impressions)],['CTR',`${(data.gsc.totals.ctr*100).toFixed(2)}%`],['Orta mövqe',data.gsc.totals.position?.toFixed(1)||'—']].map(([k,v])=><s-section key={k}><div className="seo-metric"><span>{k}</span><strong>{v}</strong><small>İdxal edilmiş sətirlər üzrə</small></div></s-section>)}</div><s-banner tone="info">{data.gsc.startDate} — {data.gsc.endDate} · {data.gsc.property}<br/>{data.gsc.note}</s-banner>{data.gsc.comparison&&<s-section heading="Əvvəlki dövrlə müqayisə"><s-paragraph>{data.gsc.comparison.startDate} — {data.gsc.comparison.endDate}: {number(data.gsc.comparison.previous.clicks)} klik, {number(data.gsc.comparison.previous.impressions)} görünmə. Klik fərqi: {number(data.gsc.totals.clicks-data.gsc.comparison.previous.clicks)}.</s-paragraph><s-paragraph color="subdued">Bu müqayisə SEO dəyişikliklərinin səbəb olduğunu sübut etmir.</s-paragraph></s-section>}<s-section heading="Yaxşılaşdırma imkanları"><s-paragraph color="subdued">100+ görünmə, 3–20 mövqe, 3%-dən aşağı CTR. Bunlar prioritetləşdirmə filtrləridir.</s-paragraph><s-table><s-table-header-row><s-table-header>Səhifə / sorğu</s-table-header><s-table-header>Klik</s-table-header><s-table-header>Görünmə</s-table-header><s-table-header>CTR</s-table-header><s-table-header>Mövqe</s-table-header></s-table-header-row><s-table-body>{data.gsc.opportunities.map(r=><s-table-row key={`${r.page}-${r.query}`}><s-table-cell>{r.query||r.page}</s-table-cell><s-table-cell>{r.clicks}</s-table-cell><s-table-cell>{r.impressions}</s-table-cell><s-table-cell>{(r.ctr*100).toFixed(2)}%</s-table-cell><s-table-cell>{r.position.toFixed(1)}</s-table-cell></s-table-row>)}</s-table-body></s-table></s-section></>:<s-section><Empty heading="Google məlumatı hələ əlavə edilməyib" text="Real klik və görünmə göstəriciləri Search Console CSV idxalından sonra görünəcək."/></s-section>}
        <GoogleImport onAction={onAction} busy={busy}/>
      </>}
      {tab==='Layihələr'&&<>
        {data.drafts.length>1&&<s-section heading="Toplu tətbiq"><s-paragraph>İlk 25 uyğun layihəni birlikdə nəzərdən keçir və təsdiqlə. Xəta baş verərsə qalan dəyişikliklər dayandırılır.</s-paragraph><s-button disabled={busy||!data.canWrite||!data.drafts.some(d=>!d.stale)} onClick={()=>setBulk(data.drafts.filter(d=>!d.stale).slice(0,25))}>Toplu dəyişiklikləri nəzərdən keçir</s-button></s-section>}
        {bulk.length>0&&<s-section heading={`${bulk.length} canlı dəyişiklik üçün təsdiq`}><s-banner tone="warning">Aşağıdakı bütün mətnlər Shopify-da dəyişəcək.</s-banner>{bulk.map(d=><div key={d.pageId}><s-heading>{d.pageTitle}</s-heading><TextPair before={d.before} after={d.after}/></div>)}<s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy} onClick={()=>onAction({intent:'bulk-apply',confirm:'APPLY',batch:JSON.stringify(bulk.map(d=>({pageId:d.pageId,draftHash:d.afterHash})))})}>Hamısını təsdiqlə və tətbiq et</s-button><s-button disabled={busy} onClick={()=>setBulk([])}>İmtina et</s-button></s-stack></s-section>}

        {confirm&&<s-section heading="Canlı dəyişiklik təsdiqi"><s-banner tone="warning">{confirm.pageTitle} səhifəsinin SEO başlığı və meta təsviri Shopify-da dəyişəcək. Aşağıdakı mətni yoxla.</s-banner><TextPair before={confirm.before} after={confirm.after}/><s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy} onClick={()=>onAction({intent:'apply',pageId:confirm.pageId,confirm:'APPLY',draftHash:confirm.afterHash})}>Təsdiqlə və Shopify-da tətbiq et</s-button><s-button disabled={busy} onClick={()=>setConfirm(null)}>İmtina et</s-button></s-stack></s-section>}
        {data.drafts.length?data.drafts.map(d=><s-section heading={d.pageTitle} key={d.pageId}>{d.stale&&<s-banner tone="warning">Səhifə mənbəyi dəyişib. Köhnə layihəni silib yenisini hazırla.</s-banner>}<TextPair before={d.before} after={d.after}/><s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy||d.stale||!data.canWrite} onClick={()=>setConfirm(d)}>Shopify-da tətbiq et</s-button><s-button disabled={busy} onClick={()=>setSelected(d.pageId)}>Redaktə et</s-button><s-button tone="critical" disabled={busy} onClick={()=>onAction({intent:'delete-draft',pageId:d.pageId})}>Layihəni sil</s-button></s-stack></s-section>):<s-section><Empty heading="Hələ düzəliş layihəsi yoxdur" text="Səhifələr bölməsində məhsulu aç, SEO mətnini redaktə edib layihə kimi saxla."/></s-section>}
      </>}
      {tab==='Tarixçə'&&<>
        <s-section heading="Yoxlama tarixçəsi"><s-table><s-table-header-row><s-table-header>Tarix</s-table-header><s-table-header>Səhifə</s-table-header><s-table-header>Tapıntı</s-table-header><s-table-header>Bal</s-table-header></s-table-header-row><s-table-body>{[...data.snapshots].reverse().map(s=><s-table-row key={s.date}><s-table-cell>{date(s.date)}</s-table-cell><s-table-cell>{s.pageCount}</s-table-cell><s-table-cell>{s.issues}</s-table-cell><s-table-cell>{s.score??'—'}</s-table-cell></s-table-row>)}</s-table-body></s-table></s-section>
        {data.changes.length?data.changes.map(c=><s-section heading={c.pageTitle} key={c.id}><s-badge tone={c.status==='applied'?'success':'warning'}>{c.status==='applied'?'Tətbiq edildi':'Nəticəni Shopify-da yoxla'} · {date(c.createdAt)}</s-badge><TextPair before={c.before} after={c.after}/>{c.status==='applied'&&!c.pageId.includes('/MediaImage/')&&<s-button disabled={busy} onClick={()=>onAction({intent:'restore-draft',changeId:c.id})}>Əvvəlki mətnə geri dönüş layihəsi hazırla</s-button>}</s-section>):<s-section><Empty heading="Canlı dəyişiklik edilməyib" text="Shopify-da təsdiqlənmiş dəyişikliklər və onların əvvəlki dəyərləri burada saxlanacaq."/></s-section>}
      </>}
      </>}
      <s-paragraph color="subdued">Bu versiya kataloq SEO sahələrini yoxlayır və təsdiqlə yeniləyir. Google indekslənməsi, Core Web Vitals və satış atribusiyası bu yoxlamaya daxil deyil.</s-paragraph>
      {data.catalog.warnings?.map(w=><s-banner tone="warning" key={w}>{w}</s-banner>)}
    </s-stack>
  </s-page>;
}
