import SeoSuitePanel from './SeoSuitePanel';
import type {SuiteData} from './SeoSuitePanel';
import { useState } from 'react';
import type { ActionInput, ActionResult, Dashboard, Draft, Page, SEO } from '../lib/types';
import './seo.css';
import GrowthPanel from './GrowthPanel';
import AnalyticsOverview from './AnalyticsOverview';
import GoogleReports from './GoogleReports';
import {GoogleConnectionView,CompressionView,BacklinksView} from './Integrations';
import { ImagesView, TechnicalView } from './PremiumFeatures';

type Props = {suite?:SuiteData;suiteOpen?:boolean;onSuiteOpen?:(open:boolean)=>void;data:Dashboard;busy:boolean;result?:ActionResult;onAction:(input:ActionInput)=>void};
const tabs = ["ABD müşterileri","Genel bakış","Sayfalar","Anahtar kelimeler","Dahili bağlantılar","Görseller","Görsel sıkıştırma","Backlinkler","Teknik SEO","SEO Merkezi","Google sonuçları","Taslaklar","Geçmiş"] as const;
type Tab = typeof tabs[number];
const number = (n:number) => new Intl.NumberFormat('tr-TR').format(n);
const date = (s:string|null) => s?`${new Date(s).toLocaleString('tr-TR',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})} UTC`:"Henüz kontrol edilmedi";
const priority = {high:"Yüksek",medium:'Orta',low:"İncele"};
function TextPair({before,after}:{before:SEO;after:SEO}) {return <div className="seo-comparison"><div><s-text color="subdued">ÖNCE</s-text><h3>{before.title||"Özel başlık yok"}</h3><p>{before.description||"Özel meta açıklama yok"}</p></div><div className="seo-after"><s-text color="subdued">ÖNERİLEN</s-text><h3>{after.title}</h3><p>{after.description||"Açıklama boş"}</p></div></div>;}
function Empty({heading,text}:{heading:string;text:string}){return <div className="seo-empty"><s-icon type="search"/><s-heading>{heading}</s-heading><s-paragraph color="subdued">{text}</s-paragraph></div>;}
function Editor({page,draft,busy,onAction,onClose}:{page:Page;draft?:Draft;busy:boolean;onAction:Props['onAction'];onClose:()=>void}){
  const [title,setTitle]=useState(draft?.after.title||page.seo.title||page.title);
  const [description,setDescription]=useState(draft?.after.description||page.seo.description||'');
  const invalid=!title.trim()||title.length>70||description.length>320;
  return <s-section heading={page.title}><div className="seo-editor"><div><s-stack gap="base" direction="block">
    <s-text-field label="SEO başlığı" value={title} maxLength={70} onInput={e=>setTitle(e.currentTarget.value)} details={`${title.length} / 70 karakter`} required/>
    <s-text-area label="Meta açıklama" value={description} rows={5} maxLength={320} onInput={e=>setDescription(e.currentTarget.value)} details={`${description.length} / 320 karakter. Yaklaşık 155 karakter bir düzenleme önerisidir.`}/>
    <s-button disabled={busy} onClick={()=>{setTitle(page.suggestion.title);setDescription(page.suggestion.description);}}>Kaynak metinden öneri hazırla</s-button>
    <s-paragraph color="subdued">{page.suggestion.note}</s-paragraph>{page.keyword&&<s-paragraph>Seçilen hedef ifade: <strong>{page.keyword}</strong>. Yalnızca ürüne uygunsa metinde doğal şekilde kullanın.</s-paragraph>}
  </s-stack></div><div className="seo-preview"><s-heading>Google önizlemesi</s-heading><div className="seo-snippet"><small>{page.url||"Sayfa online mağazada yayınlanmamış"}</small><h3>{title}</h3><p>{description||"Meta açıklama burada görünecek."}</p></div><s-paragraph color="subdued">Yaklaşık görünümdür. Google, sorguya göre farklı bir metin gösterebilir.</s-paragraph></div></div>
  <s-stack gap="base" direction="inline"><s-button variant="primary" disabled={busy||invalid||draft?.stale} onClick={()=>onAction({intent:'save-draft',pageId:page.id,title,description})}>Taslağı kaydet</s-button><s-button disabled={busy} onClick={onClose}>Kapat</s-button>{page.url&&<s-link href={page.url} target="_blank">Canlı sayfayı aç</s-link>}</s-stack>
  {draft?.stale&&<s-banner tone="warning">Bu taslağın kaynak bilgileri değişti. Taslaklar bölümünde eski taslağı silip yenisini hazırlayın.</s-banner>}
  <div className="seo-findings">{page.issues.map(i=><div className="seo-finding" key={i.code}><s-badge tone={i.severity==='high'?'critical':i.severity==='medium'?'warning':'info'}>{priority[i.severity]}</s-badge><div><strong>{i.label}</strong><p>{i.detail}</p></div></div>)}</div></s-section>;
}
function KeywordRow({page,busy,mapping,onAction,duplicate}:{page:Page;busy:boolean;mapping:string;onAction:Props['onAction'];duplicate:boolean}){
  const [keyword,setKeyword]=useState(mapping);
  return <s-table-row><s-table-cell>{page.title}</s-table-cell><s-table-cell><div className="seo-keyword"><s-text-field label="Hedef ifade" labelAccessibilityVisibility="exclusive" value={keyword} maxLength={150} onInput={e=>setKeyword(e.currentTarget.value)}/><s-button disabled={busy} onClick={()=>onAction({intent:'keyword',pageId:page.id,keyword})}>Kaydet</s-button></div></s-table-cell><s-table-cell>{duplicate?<s-badge tone="warning">Birden fazla sayfada</s-badge>:mapping?<s-badge>Atandı</s-badge>:<s-text color="subdued">Atanmadı</s-text>}</s-table-cell></s-table-row>;
}
function GoogleImport({onAction,busy}:{onAction:Props['onAction'];busy:boolean}){
  const [start,setStart]=useState(''),[end,setEnd]=useState(''),[property,setProperty]=useState('sc-domain:nosweatusa.com'),[csv,setCsv]=useState(''),[error,setError]=useState('');
  return <s-section heading="Search Console CSV ekle"><s-stack direction="block" gap="base"><s-paragraph>Search Console → Performance → Search results → Export. ZIP dosyasını açın; İngilizce Pages.csv veya Queries.csv dosyasını seçin.</s-paragraph><div className="seo-form-grid"><s-date-field label="Başlangıç tarihi" value={start} onChange={e=>setStart(e.currentTarget.value)}/><s-date-field label="Bitiş tarihi" value={end} onChange={e=>setEnd(e.currentTarget.value)}/></div><s-text-field label="Mülk" value={property} onInput={e=>setProperty(e.currentTarget.value)}/><label className="seo-file-label">CSV dosyası (en fazla 2 MB)<input aria-label="Search Console CSV dosyası" type="file" accept=".csv,text/csv" onChange={async e=>{const file=(e.currentTarget as HTMLInputElement).files?.[0];setError('');setCsv('');if(!file)return;if(file.size>2_000_000){setError("Dosya 2 MB’den büyük.");return;}setCsv(await file.text());}}/></label>{error&&<s-banner tone="critical">{error}</s-banner>}<s-button variant="primary" disabled={busy||!csv||!start||!end||!property} onClick={()=>onAction({intent:'gsc-import',csv,startDate:start,endDate:end,property})}>İçe aktar</s-button><s-paragraph color="subdued">Tarihleri ve ülke/cihaz/arama türü filtrelerini dışa aktarımla aynı tutun. Yukarıdaki bölümden Google hesabını bağlayarak CSV olmadan da rapor getirebilirsiniz.</s-paragraph></s-stack></s-section>;
}
export default function SeoDashboard({data,busy,result,onAction,suite,suiteOpen=false,onSuiteOpen}:Props){
  const [localTab,setTab]=useState<Tab>("Genel bakış"),[search,setSearch]=useState(''),[kind,setKind]=useState('all'),[selected,setSelected]=useState<string|null>(null),[confirm,setConfirm]=useState<Draft|null>(null),[copied,setCopied]=useState(''),[bulk,setBulk]=useState<Draft[]>([]);
  const tab=suiteOpen?"SEO Merkezi":localTab;
  const [handledResult,setHandledResult]=useState(result);
  if(result!==handledResult){setHandledResult(result);if(result?.ok){setConfirm(null);setBulk([]);if(result.message?.startsWith("Taslak kaydedildi")){setSelected(null);setTab("Taslaklar");}}}
  const pages=data.catalog.pages,issues=pages.flatMap(p=>p.issues.map(i=>({...i,page:p})));
  const current=pages.find(p=>p.id===selected);
  const filtered=pages.filter(p=>(kind==='all'||p.type===kind)&&`${p.title} ${p.handle}`.toLowerCase().includes(search.toLowerCase()));
  const keywordCounts=Object.values(data.mappings).reduce<Record<string,number>>((a,k)=>{if(k.trim())a[k.toLowerCase()]=(a[k.toLowerCase()]||0)+1;return a;},{});
  const pageTable=(items:Page[]) => <s-table><s-table-header-row><s-table-header listSlot="primary">Sayfa</s-table-header><s-table-header>Tür</s-table-header><s-table-header>Kontrol puanı</s-table-header><s-table-header>Bulgular</s-table-header><s-table-header>İşlem</s-table-header></s-table-header-row><s-table-body>{items.map(p=><s-table-row key={p.id}><s-table-cell><strong>{p.title}</strong><div className="seo-url">/{p.type==='product'?'products':'collections'}/{p.handle}</div></s-table-cell><s-table-cell><s-badge>{p.type==='product'?"Ürün":'Koleksiyon'}</s-badge></s-table-cell><s-table-cell>{p.score}/100</s-table-cell><s-table-cell>{p.issues.length?<s-badge tone={p.issues.some(i=>i.severity==='high')?'critical':'warning'}>{p.issues.length} bulgu</s-badge>:<s-badge tone="success">Geçti</s-badge>}</s-table-cell><s-table-cell><s-button disabled={busy} onClick={()=>setSelected(p.id)}>İncele</s-button></s-table-cell></s-table-row>)}</s-table-body></s-table>;
  const topIssues=[...issues].sort((a,b)=>({high:0,medium:1,low:2}[a.severity]-{high:0,medium:1,low:2}[b.severity])).slice(0,5);
  const navigate=(section:string)=>{if(!(tabs as readonly string[]).includes(section))return;setTab(section==='SEO Merkezi'?'Genel bakış':section as Tab);onSuiteOpen?.(section==='SEO Merkezi');setSelected(null);setConfirm(null);setBulk([]);};
  const icons = ['target','home','collection','search','link','image','arrows-in-horizontal','connect','code','apps','chart-line','compose','clock'] as const;
  return <div className="studio-shell">
    <a className="studio-skip" href="#studio-content">İçeriğe geç</a>
    <aside className="studio-sidebar" aria-label="Uygulama menüsü">
      <button className="studio-mark" aria-label="No Sweat SEO ana sayfa" title="No Sweat SEO" onClick={()=>navigate('Genel bakış')}><span className="studio-logo-symbol"><img src="/brand/no-sweat-logo.png" alt="" width="400" height="165"/></span></button>
      <nav className="studio-navigation" aria-label="SEO bölümleri">{tabs.map((t,i)=><button key={t} className={tab===t?'studio-nav-item active':'studio-nav-item'} aria-label={t} aria-current={tab===t?'page':undefined} title={t} onClick={()=>navigate(t)}><s-icon type={icons[i]}/><span>{t}</span>{t==='Taslaklar'&&data.drafts.length>0&&<small>{data.drafts.length}</small>}</button>)}</nav>
      <div className="studio-nav-extras"><a href="/app/competitors" title="Rakip SEO" aria-label="Rakip SEO"><s-icon type="chart-vertical"/></a><a href="/app/backlink-import" title="Backlink karşılaştırması" aria-label="Backlink karşılaştırması"><s-icon type="import"/></a></div>
    </aside>
    <main className="studio-main" id="studio-content">
      <header className="studio-header"><div><div className="studio-brand"><span className="studio-brand-symbol"><span className="studio-logo-symbol"><img src="/brand/no-sweat-logo.png" alt="No Sweat simgesi" width="400" height="165"/></span></span><span className="studio-eyebrow">SEO STUDIO</span></div><h1>{current?current.title:tab}</h1><p>Son güncelleme: {date(data.catalog.syncedAt)}</p></div><div className="studio-header-actions">{tab!=="SEO Merkezi"&&tab!=="Backlinkler"&&<><button className="studio-export" disabled={busy||!pages.length} onClick={()=>onAction({intent:'export'})}><s-icon type="export"/> Denetim CSV</button><button className="studio-primary" disabled={busy} onClick={()=>onAction({intent:'sync'})}><s-icon type="refresh"/>{busy?'İşleniyor…':'Kataloğu kontrol et'}</button></>}</div></header>
      <div className="studio-content" aria-busy={busy}>
      {tab!=="SEO Merkezi"&&result?.error&&<s-banner tone="critical" heading="İşlem başarısız">{result.error}</s-banner>}
      {tab!=="SEO Merkezi"&&result?.message&&<s-banner tone="success">{result.message}</s-banner>}
      {!data.canWrite&&<s-banner tone="info">Salt okunur mod. Canlı uygulama için mağaza sahibinin uygulamaya write_products izni vermesi gerekir.</s-banner>}
      {current?<Editor key={current.id} page={current} draft={data.drafts.find(d=>d.pageId===current.id)} busy={busy} onAction={onAction} onClose={()=>setSelected(null)}/>:<>
      {tab==="ABD müşterileri"&&<GrowthPanel data={data} busy={busy} onAction={onAction} onEdit={setSelected} onNavigate={section=>{if((tabs as readonly string[]).includes(section))setTab(section as Tab);}}/>}
      {tab==="Genel bakış"&&<><AnalyticsOverview data={data} busy={busy} onAction={onAction} onNavigate={navigate} onEdit={setSelected}/>{topIssues.length>0&&<details className="studio-details"><summary>Öncelikli bulgular <span>{issues.length} bulgu</span></summary><s-section>{topIssues.map((i,n)=><div className="seo-priority" key={`${i.page.id}-${i.code}`}><span className="seo-index">0{n+1}</span><div><strong>{i.label}</strong><p>{i.page.title}</p></div><s-badge tone={i.severity==='high'?'critical':i.severity==='medium'?'warning':'info'}>{priority[i.severity]}</s-badge><s-button disabled={busy} onClick={()=>setSelected(i.page.id)}>İncele</s-button></div>)}</s-section></details>}</>}
      {tab==="Sayfalar"&&<s-section heading="Ürünler ve koleksiyonlar"><div className="seo-filters"><s-search-field label="Sayfa ara" value={search} placeholder="Ürün adı veya URL tanıtıcısı" onInput={e=>setSearch(e.currentTarget.value)}/><s-select label="Sayfa türü" value={kind} onChange={e=>setKind(e.currentTarget.value)}><s-option value="all">Tümü</s-option><s-option value="product">Ürünler</s-option><s-option value="collection">Koleksiyonlar</s-option></s-select></div><s-button disabled={busy||!filtered.length||filtered.length>100} onClick={()=>onAction({intent:'bulk-draft',pageIds:JSON.stringify(filtered.map(p=>p.id))})}>Bu liste için toplu SEO taslağı hazırla</s-button>{filtered.length?pageTable(filtered):<Empty heading="Sayfa bulunamadı" text="Kataloğu getirin veya arama filtresini değiştirin."/>}</s-section>}
      {tab==="Anahtar kelimeler"&&<s-section heading="Anahtar kelime haritası"><s-paragraph color="subdued">Her sayfaya ürüne uygun bir ana ifade atayın. Yinelenen hedef uyarısı, otomatik olarak rekabet sorunu olduğunu kanıtlamaz. Bu araç arama hacmini hesaplamaz.</s-paragraph><s-table><s-table-header-row><s-table-header>Sayfa</s-table-header><s-table-header>Hedef ifade</s-table-header><s-table-header>Durum</s-table-header></s-table-header-row><s-table-body>{pages.map(p=><KeywordRow key={p.id} page={p} busy={busy} mapping={data.mappings[p.id]||''} duplicate={keywordCounts[(data.mappings[p.id]||'').toLowerCase()]>1} onAction={onAction}/>)}</s-table-body></s-table></s-section>}
      {tab==="Dahili bağlantılar"&&<s-section heading="Dahili bağlantı önerileri"><s-paragraph color="subdued">Başlık ve etiketlerdeki ortak kelimelere dayanır. HTML’yi yalnızca bağlantının faydalı olduğu metne ekleyin. Bağlantılar otomatik yerleştirilmez.</s-paragraph>{copied&&<s-banner tone="info">{copied}</s-banner>}{data.links.length?data.links.map(l=><div className="seo-link-row" key={`${l.fromId}-${l.toId}`}><div><small>BU SAYFADAN</small><strong>{l.fromTitle}</strong></div><span>→</span><div><small>BU SAYFAYA</small><strong>{l.toTitle}</strong><p>Ortak kelimeler: {l.common.join(', ')}</p></div><s-button onClick={async()=>{const html=`<a href="${l.toUrl.replaceAll('&','&amp;').replaceAll('"','&quot;')}">${l.anchor.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}</a>`;try{await navigator.clipboard.writeText(html);setCopied("Bağlantı HTML’si kopyalandı.");}catch{setCopied(html);}}}>HTML’yi kopyala</s-button></div>):<Empty heading="Uygun bağlantı önerisi yok" text="İlgili sayfalar getirildikçe başlık ve etiketlere göre öneriler burada görünecek."/>}</s-section>}
      {tab==="Görseller"&&<ImagesView data={data} busy={busy} onAction={onAction}/>}
      {tab==="SEO Merkezi"&&suite&&<SeoSuitePanel embedded data={suite} busy={busy} result={result} canManage={Boolean(data.canManageGoogle)} onAction={onAction}/>}
      {tab==="Teknik SEO"&&<TechnicalView data={data} busy={busy} onAction={onAction}/>}
      {tab==="Görsel sıkıştırma"&&<CompressionView data={data} busy={busy} onAction={onAction}/>}
      {tab==="Backlinkler"&&<BacklinksView data={data} busy={busy} onAction={onAction}/>}
      {tab==="Google sonuçları"&&<>
        <GoogleConnectionView key={String(data.google?.connected)+data.google?.property} data={data} busy={busy} onAction={onAction} result={result}/>
        <GoogleReports data={data} busy={busy} onAction={onAction}/>
        <details className="studio-details"><summary>Alternatif: CSV içe aktar</summary>{data.gsc&&<s-paragraph>Son içe aktarılan rapor: {data.gsc.property} · {data.gsc.startDate} — {data.gsc.endDate}. {number(data.gsc.totals.clicks)} tıklama · {number(data.gsc.totals.impressions)} gösterim · CTR %{(data.gsc.totals.ctr*100).toLocaleString('tr-TR',{maximumFractionDigits:2})}. {data.gsc.note}</s-paragraph>}<GoogleImport onAction={onAction} busy={busy}/></details>
      </>}
      {tab==="Taslaklar"&&<>
        {data.drafts.length>1&&<s-section heading="Toplu uygula"><s-paragraph>İlk 25 uygun taslağı birlikte inceleyip onaylayın. Hata oluşursa kalan değişiklikler durdurulur.</s-paragraph><s-button disabled={busy||!data.canWrite||!data.drafts.some(d=>!d.stale)} onClick={()=>setBulk(data.drafts.filter(d=>!d.stale).slice(0,25))}>Toplu değişiklikleri incele</s-button></s-section>}
        {bulk.length>0&&<s-section heading={`${bulk.length} canlı değişiklik için onay`}><s-banner tone="warning">Aşağıdaki tüm metinler Shopify’da değişecek.</s-banner>{bulk.map(d=><div key={d.pageId}><s-heading>{d.pageTitle}</s-heading><TextPair before={d.before} after={d.after}/></div>)}<s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy} onClick={()=>onAction({intent:'bulk-apply',confirm:'APPLY',batch:JSON.stringify(bulk.map(d=>({pageId:d.pageId,draftHash:d.afterHash})))})}>Tümünü onayla ve uygula</s-button><s-button disabled={busy} onClick={()=>setBulk([])}>Vazgeç</s-button></s-stack></s-section>}

        {confirm&&<s-section heading="Canlı değişiklik onayı"><s-banner tone="warning">{confirm.pageTitle} sayfasının SEO başlığı ve meta açıklaması Shopify’da değişecek. Aşağıdaki metni kontrol edin.</s-banner><TextPair before={confirm.before} after={confirm.after}/><s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy} onClick={()=>onAction({intent:'apply',pageId:confirm.pageId,confirm:'APPLY',draftHash:confirm.afterHash})}>Onayla ve Shopify’da uygula</s-button><s-button disabled={busy} onClick={()=>setConfirm(null)}>Vazgeç</s-button></s-stack></s-section>}
        {data.drafts.length?data.drafts.map(d=><s-section heading={d.pageTitle} key={d.pageId}>{d.stale&&<s-banner tone="warning">Sayfanın kaynak bilgileri değişti. Eski taslağı silip yenisini hazırlayın.</s-banner>}<TextPair before={d.before} after={d.after}/><s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy||d.stale||!data.canWrite} onClick={()=>setConfirm(d)}>Shopify’da uygula</s-button><s-button disabled={busy} onClick={()=>setSelected(d.pageId)}>Düzenle</s-button><s-button tone="critical" disabled={busy} onClick={()=>onAction({intent:'delete-draft',pageId:d.pageId})}>Taslağı sil</s-button></s-stack></s-section>):<s-section><Empty heading="Henüz düzenleme taslağı yok" text="Sayfalar bölümünde ürünü açın, SEO metnini düzenleyip taslak olarak kaydedin."/></s-section>}
      </>}
      {tab==="Geçmiş"&&<>
        <s-section heading="Kontrol geçmişi"><s-table><s-table-header-row><s-table-header>Tarih</s-table-header><s-table-header>Sayfa</s-table-header><s-table-header>Bulgu</s-table-header><s-table-header>Puan</s-table-header></s-table-header-row><s-table-body>{[...data.snapshots].reverse().map(s=><s-table-row key={s.date}><s-table-cell>{date(s.date)}</s-table-cell><s-table-cell>{s.pageCount}</s-table-cell><s-table-cell>{s.issues}</s-table-cell><s-table-cell>{s.score??'—'}</s-table-cell></s-table-row>)}</s-table-body></s-table></s-section>
        {data.changes.length?data.changes.map(c=><s-section heading={c.pageTitle} key={c.id}><s-badge tone={c.status==='applied'?'success':'warning'}>{c.status==='applied'?"Uygulandı":"Sonucu Shopify’da kontrol et"} · {date(c.createdAt)}</s-badge><TextPair before={c.before} after={c.after}/>{c.status==='applied'&&!c.pageId.includes('/MediaImage/')&&<s-button disabled={busy} onClick={()=>onAction({intent:'restore-draft',changeId:c.id})}>Önceki metne dönüş taslağı hazırla</s-button>}</s-section>):<s-section><Empty heading="Canlı değişiklik yapılmadı" text="Shopify’da doğrulanan değişiklikler ve önceki değerleri burada saklanacak."/></s-section>}
      </>}
      </>}
      <details className="studio-details studio-scope"><summary>Kontrol kapsamı ve notlar</summary><s-paragraph color="subdued">Bu sürüm, katalog SEO alanlarını kontrol eder ve onayla günceller. Google dizine ekleme, Core Web Vitals ve satış ilişkilendirmesi bu kontrole dahil değildir.</s-paragraph>
      {data.catalog.warnings?.map(w=><s-banner tone="warning" key={w}>{w}</s-banner>)}</details>
    </div>
    </main>
  </div>;
}
