import {useState} from 'react';
import type {ActionInput,ActionResult} from '../lib/types';
import {suiteTemplates} from '../lib/seo-suite.mjs';
import './seo-suite.css';
import AuditWizard from './AuditWizard';
import type {AuditConfig} from './AuditWizard';
type Keyword={keyword:string;device?:string;position:number|null;previous?:number|null;change?:number|null;volume?:number|null;difficulty?:number|null;url?:string;domain?:string;kind?:string;ownPosition?:number|null};
type Backlink={source:string;target:string;status:string;anchor:string};
type Report<T>={observedAt:string;provider:string;importedAt:string;limited:boolean;rows:T[]};
type Finding={type:string;url:string;detail:string};
type Audit={checkedAt:string;pages:{url:string;status:number|null;elapsedMs?:number;redirects:{from:string;to:string;status:number}[]}[];findings:Finding[];warnings:string[];partial:boolean};
export type SuiteData={auditConfig?:AuditConfig;settings:{keywords:string[];competitors:string[];auto:boolean;providerAuto:boolean};providerConfigured:boolean;ranks:Report<Keyword>[];rankChanges:Keyword[];domainReports:Record<string,Report<Keyword>>;gaps:Keyword[];keywords:Report<Keyword>|null;backlinks:Report<Backlink>|null;audits:Audit[];alerts:{id:string;at:string;title:string;detail:string;read:boolean}[];digests:{at:string;day:string;traffic:{clicks:number;impressions:number;startDate:string;endDate:string;importedAt:string}|null;auditPages:number;auditFindings:number;auditAt:string|null;rankRows:number;backlinkRows:number;newAlerts:number}[];runs:{at:string;steps:string[];errors:string[]}[];lastDailyAt?:string;speed?:{checkedAt:string;url:string;rows:{device:string;score?:number;lcp?:string;cls?:string;tbt?:string;error?:string}[]}};
const tabs=['Konum takibi','Rakip kelime farkı','Kelime araştırması','Backlink keşfi','Geniş site denetimi','Raporlar ve uyarılar','Ayarlar'] as const;
const fmt=(value:unknown)=>value===null||value===undefined?'—':typeof value==='number'?value.toLocaleString('tr-TR'):String(value);
function Table({headers,rows}:{headers:string[];rows:unknown[][]}){const [count,setCount]=useState(50);return rows.length?<><div className="suite-table-scroll"><table><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.slice(0,count).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{fmt(v)}</td>)}</tr>)}</tbody></table></div>{rows.length>count&&<s-button onClick={()=>setCount(count+50)}>Sonraki 50 satır</s-button>}</>:<p className="suite-empty">Henüz veri yok. Gerçek bir rapor yükleyin veya veri bağlantısını kullanın.</p>;}
function Source({report}:{report?:{observedAt:string;provider:string;limited:boolean}|null}){return report?<p className="suite-source">Kaynak: {report.provider} · Veri tarihi: {report.observedAt} {report.limited?'· Sınırlı rapor / tam kapsam garanti edilmez.':''}</p>:null;}
function Importer({kind,data,busy,onAction}:{kind:string;data:SuiteData;busy:boolean;onAction:(i:ActionInput)=>void}){
 const [csv,setCSV]=useState(''),[provider,setProvider]=useState(''),[date,setDate]=useState(''),[domain,setDomain]=useState('nosweatusa.com'),[error,setError]=useState('');
 const template=suiteTemplates[kind as keyof typeof suiteTemplates];
 return <details className="suite-import"><summary>Gerçek CSV raporu yükle</summary><p>ABD · İngilizce. Sağlayıcınızın dışa aktarımını aşağıdaki sütunlara dönüştürün. Boş sayılar bilinmeyen değerdir.</p><code>{template.trim()}</code><s-stack direction="block" gap="base">
 <s-text-field label="Veri kaynağı (ör. Semrush CSV)" value={provider} onInput={e=>setProvider(e.currentTarget.value)}/><s-date-field label="Raporun veri tarihi" value={date} onChange={e=>setDate(e.currentTarget.value)}/>
 {kind==='gaps'&&<s-select label="Raporun sitesi" value={domain} onChange={e=>setDomain(e.currentTarget.value)}>{['nosweatusa.com',...data.settings.competitors].map(d=><s-option key={d} value={d}>{d}</s-option>)}</s-select>}
 {kind==='ranks'&&<p>device: mobile / desktop. position: 1–100; boşsa ilk 100 içinde bulunamadı. URL yalnızca mağazanıza ait olmalıdır.</p>}{kind==='gaps'&&<p>Konumlar masaüstü organik sıralamadır. Kendi siteniz ve rakip için aynı tarih ve sağlayıcıyı kullanın.</p>}{kind==='backlinks'&&<p>status: active / new / lost. Kayıp durumu sağlayıcının açıkça bildirdiği veriye dayanmalıdır.</p>}
 <label className="suite-file">CSV dosyası<input type="file" accept=".csv,text/csv" onChange={async e=>{setError('');setCSV('');const f=(e.currentTarget as HTMLInputElement).files?.[0];if(!f)return;if(f.size>2_000_000){setError('Dosya 2 MB sınırını aşıyor.');return;}setCSV(await f.text());}}/></label>{error&&<s-banner tone="critical">{error}</s-banner>}
 <s-button disabled={busy||!csv||!provider.trim()||!date} onClick={()=>onAction({intent:'suite-import',kind,csv,provider,date,domain})}>CSV raporunu kaydet</s-button></s-stack></details>;
}
export default function SeoSuitePanel({data,busy,result,canManage,onAction}:{data:SuiteData;busy:boolean;result?:ActionResult;canManage:boolean;onAction:(input:ActionInput)=>void}){
 const [tab,setTab]=useState<(typeof tabs)[number]>('Konum takibi'),[keywords,setKeywords]=useState(data.settings.keywords.join('\n')),[competitors,setCompetitors]=useState(data.settings.competitors.join('\n')),[auto,setAuto]=useState(data.settings.auto),[paid,setPaid]=useState(data.settings.providerAuto);
 const [wizard,setWizard]=useState(false);
 const audit=data.audits.slice(-1)[0],latest=data.ranks.slice(-1)[0],digest=data.digests.slice(-1)[0],unread=data.alerts.filter(a=>!a.read).length;
 const fetchButton=(kind:string)=><s-button disabled={busy||!data.providerConfigured||!canManage} onClick={()=>onAction({intent:'suite-provider',kind})}>DataForSEO’dan güncelle</s-button>;
 return <div className="suite-shell"><header className="suite-header"><div><a href="/app">← Genel bakış</a><p className="suite-kicker">NOWUSA · GELİŞMİŞ SEO</p><h1>SEO Merkezi</h1><p>Araştırma, teknik denetim ve günlük takip tek çalışma alanında.</p></div><s-button disabled={busy} onClick={()=>onAction({intent:'suite-export'})}>CSV raporunu indir</s-button></header>
 <div className="suite-status"><span>ABD · İngilizce</span><span>{data.providerConfigured?'DataForSEO yapılandırıldı':'Harici veri: CSV / API bağlantısı bekleniyor'}</span><span>{unread} okunmamış uyarı</span></div>
 <nav className="suite-tabs" aria-label="SEO Merkezi bölümleri">{tabs.map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <main aria-busy={busy} className="suite-content">{busy&&<s-banner tone="info">İşleniyor… Rapor tamamlanana kadar mevcut veriler gösterilir.</s-banner>}{result?.error&&<s-banner tone="critical">{result.error}</s-banner>}{result?.message&&<s-banner tone={result.ok===false?'warning':'success'}>{result.message}</s-banner>}
 {!data.providerConfigured&&['Konum takibi','Rakip kelime farkı','Kelime araştırması','Backlink keşfi'].includes(tab)&&<s-banner tone="info">Otomatik keşif için DataForSEO hesabı gerekir. API anahtarı tarayıcıda saklanmaz. Bu sırada gerçek sağlayıcı raporlarını CSV ile yükleyebilirsiniz. Örnek veya uydurma metrik gösterilmez.</s-banner>}
 {tab==='Konum takibi'&&<s-section heading="Günlük Google konum takibi"><p>Seçtiğiniz ifadelerde ABD organik ilk 100 sonucu, mobil ve masaüstü ayrı izlenir. Bu ölçüm Search Console ortalama konumundan farklıdır.</p>{fetchButton('ranks')}<Source report={latest}/><Table headers={['İfade','Cihaz','Konum','Önceki','Değişim','URL']} rows={data.rankChanges.map(r=>[r.keyword,r.device,r.position??'İlk 100’de yok',r.previous,r.change,r.url])}/><details><summary>Ölçüm geçmişi ({data.ranks.length})</summary><Table headers={['Tarih','Kaynak','Satır']} rows={[...data.ranks].reverse().map(r=>[r.observedAt,r.provider,r.rows.length])}/></details><Importer kind="ranks" data={data} busy={busy} onAction={onAction}/></s-section>}
 {tab==='Rakip kelime farkı'&&<s-section heading="Rakiplerin daha güçlü olduğu ifadeler"><p>Yalnızca aynı tarih, ülke, cihaz ve sağlayıcı kapsamındaki raporlar karşılaştırılır. “Kendi raporunda bulunamadı” sıralama olmadığı anlamına gelmez.</p>{fetchButton('gaps')}<Table headers={['Site','Veri tarihi','Kaynak','Satır']} rows={Object.entries(data.domainReports).map(([d,r])=>[d,r.observedAt,r.provider,r.rows.length])}/><Table headers={['İfade','Rakip','Rakip konumu','Sizin konumunuz','Aylık hacim','Durum']} rows={data.gaps.map(r=>[r.keyword,r.domain,r.position,r.ownPosition,r.volume,r.kind])}/><Importer kind="gaps" data={data} busy={busy} onAction={onAction}/></s-section>}
 {tab==='Kelime araştırması'&&<s-section heading="Arama hacmi ve anahtar kelime zorluğu"><p>ABD için sağlayıcının tahmini aylık arama hacmi ve 0–100 SEO zorluk metriği. Zorluk Google’ın puanı değildir; boş değer sıfır sayılmaz.</p>{fetchButton('keywords')}<Source report={data.keywords}/><Table headers={['İfade','Aylık hacim','SEO zorluğu']} rows={(data.keywords?.rows||[]).map(r=>[r.keyword,r.volume,r.difficulty])}/><Importer kind="keywords" data={data} busy={busy} onAction={onAction}/></s-section>}
 {tab==='Backlink keşfi'&&<s-section heading="Yeni ve kayıp backlinkler"><p>Sağlayıcı indeksinden keşfedilen bağlantılar. Liste dışına düşen bir satır otomatik olarak kayıp sayılmaz; yeni/kayıp durumu kaynaktan alınır.</p>{fetchButton('backlinks')}<Source report={data.backlinks}/><Table headers={['Kaynak URL','Hedef URL','Durum','Bağlantı metni']} rows={(data.backlinks?.rows||[]).map(r=>[r.source,r.target,({active:'Aktif',new:'Yeni',lost:'Kayıp'} as Record<string,string>)[r.status],r.anchor])}/><Importer kind="backlinks" data={data} busy={busy} onAction={onAction}/></s-section>}
 {tab==='Geniş site denetimi'&&<><s-section heading="Site taraması"><p>Ana sayfa, katalog, site haritaları ve keşfedilen bağlantılar taranır. En fazla 60 sayfa, 4 site haritası ve 3 dakika; sonuçlar bu kapsama aittir. JavaScript çalıştırılmaz.</p><s-button disabled={busy||!canManage} onClick={()=>setWizard(true)}>Yeni denetim oluştur</s-button>{wizard&&<AuditWizard initial={data.auditConfig} busy={busy} canManage={canManage} onAction={onAction} onClose={()=>setWizard(false)}/>}{audit&&<><p>{audit.checkedAt} · {audit.pages.length} sayfa · {audit.findings.length} bulgu</p>{audit.warnings.map(w=><s-banner tone="warning" key={w}>{w}</s-banner>)}<Table headers={['Bulgu','URL','Ayrıntı']} rows={audit.findings.map(f=>[f.type,f.url,f.detail])}/><details><summary>Taranan sayfalar ve yönlendirmeler</summary><Table headers={['URL','HTTP','HTML yanıtı (ms)','Yönlendirme yolu']} rows={audit.pages.map(p=>[p.url,p.status,p.elapsedMs,p.redirects.map(r=>`${r.status}: ${r.from} → ${r.to}`).join(' | ')])}/></details></>}</s-section>
 <s-section heading="Google PageSpeed · ana sayfa"><p>Mobil ve masaüstü Lighthouse laboratuvar ölçümü. Gerçek kullanıcı Core Web Vitals ölçümü değildir; API kotası nedeniyle veri alınamayabilir.</p><s-button disabled={busy} onClick={()=>onAction({intent:'suite-speed'})}>Hız ölçümünü getir</s-button>{data.speed&&<Table headers={['Cihaz','Performans / 100','LCP','CLS','TBT','Durum']} rows={data.speed.rows.map(r=>[r.device,r.score,r.lcp,r.cls,r.tbt,r.error||'Ölçüldü'])}/>}</s-section></>}
 {tab==='Raporlar ve uyarılar'&&<><s-section heading="Günlük rapor ve bildirim merkezi"><p>Uyarılar uygulama içinde saklanır. Trafikte en az 20 önceki tıklama ve %30 düşüş, 5+ konum gerilemesi, kırık sayfa, noindex ve sağlayıcının bildirdiği kayıp backlinkler izlenir.</p><s-button disabled={busy} onClick={()=>onAction({intent:'suite-digest'})}>Özeti şimdi oluştur</s-button>{digest&&<div className="suite-summary"><strong>{digest.day}</strong><p>{digest.auditPages} taranan sayfa · {digest.auditFindings} teknik bulgu · {digest.rankRows} sıralama ölçümü · {digest.newAlerts} yeni uyarı</p>{digest.traffic&&<p>ABD Google: {digest.traffic.clicks} tıklama / {digest.traffic.impressions} gösterim · {digest.traffic.startDate} — {digest.traffic.endDate}. Son veri: {digest.traffic.importedAt}</p>}</div>}
 {[...data.alerts].reverse().map(a=><article className="suite-alert" key={a.id}><div><strong>{a.title}</strong><p>{a.detail}</p><small>{a.at}</small></div>{a.read?<span>Okundu</span>:<s-button disabled={busy} onClick={()=>onAction({intent:'suite-read',id:a.id})}>Okundu</s-button>}</article>)}{!data.alerts.length&&<p className="suite-empty">Henüz uyarı oluşmadı. Veri yokluğu, sorun olmadığı anlamına gelmez.</p>}</s-section>
 <s-section heading="Günlük çalışma geçmişi"><p>Son çalışma: {data.lastDailyAt||'Henüz çalışmadı'}. Otomasyon için günlük zamanlayıcının bağlı olması gerekir.</p><Table headers={['Tarih','Tamamlanan işler','Hatalar']} rows={[...data.runs].reverse().map(r=>[r.at,r.steps.join(', '),r.errors.join(' · ')||'Yok'])}/><details><summary>Kaydedilen özetler</summary><Table headers={['Gün','Taranan sayfa','Bulgu','Yeni uyarı']} rows={[...data.digests].reverse().map(d=>[d.day,d.auditPages,d.auditFindings,d.newAlerts])}/></details></s-section></>}
 {tab==='Ayarlar'&&<s-section heading="İzleme ayarları"><s-stack direction="block" gap="base"><s-text-area label="Takip ve araştırma ifadeleri (satır başına bir, en fazla 10)" rows={6} value={keywords} onInput={e=>setKeywords(e.currentTarget.value)}/><s-text-area label="Rakip alan adları (satır başına bir, en fazla 3)" rows={3} value={competitors} onInput={e=>setCompetitors(e.currentTarget.value)}/><s-checkbox label="Günlük site denetimi ve uygulama içi raporları etkinleştir" checked={auto} onChange={e=>setAuto(e.currentTarget.checked)}/><s-checkbox label="Günlük ücretli sağlayıcı sorgularını da etkinleştir" checked={paid} disabled={!data.providerConfigured} onChange={e=>setPaid(e.currentTarget.checked)}/><p>Ücretli sorgular ayrıca açılır. Tam günlük çalışma: ifade başına 2 sıralama isteği, 1 kelime isteği, site başına 1 rakip isteği ve 1 backlink isteği. Sağlayıcı bakiyesi kullanılır; uygulama ücretli hesap açmaz.</p><s-button disabled={busy||!canManage} variant="primary" onClick={()=>onAction({intent:'suite-settings',keywords,competitors,auto:String(auto),providerAuto:String(paid)})}>Ayarları kaydet</s-button><s-button disabled={busy||!canManage||!data.settings.auto} onClick={()=>onAction({intent:'suite-daily'})}>Günlük işleri şimdi çalıştır</s-button><p>Bağlantı: {data.providerConfigured?'DataForSEO hazır':'DataForSEO API hesabı henüz yapılandırılmadı'}. Günlük zamanlayıcı ve API bilgileri sunucuda güvenli saklanır.</p></s-stack></s-section>}
 </main></div>;
}
