import {useState} from 'react';
import type {ActionInput,ActionResult} from '../lib/types';
import {TRAFFIC_PERIODS,countryFlag} from '../lib/traffic.mjs';
import './traffic.css';
import LiveVisitors from './LiveVisitors';

type Metrics={sessions:number;totalUsers:number;screenPageViews:number};
type Source={sessionSource:string;sessionMedium:string;sessionCampaignName:string;sessionDefaultChannelGroup:string;country:string;countryId:string;label:string;sessions:number;totalUsers:number};
type Product=Source&{path:string;title:string;image:string;screenPageViews:number};
export type TrafficReport={period:string;start:string;end:string;previousStart:string;previousEnd:string;timeZone:string;partial:boolean;generatedAt:string;property:string;name:string;current:Metrics;previous:Metrics;daily:(Metrics&{date:string})[];sources:Source[];countries:{country:string;countryId:string;sessions:number;totalUsers:number}[];products:Product[];quality:{limited:boolean;thresholded:boolean;otherRow:boolean;sampled:boolean}};
export type TrafficData={auto:boolean;reports:Record<string,TrafficReport>;connection:{connected:boolean;configured:boolean;serviceEmail:string;property:string;name:string;timeZone:string;measurementId:string;properties:{property:string;name:string}[]}};
type Props={data?:TrafficData;busy:boolean;result?:ActionResult;onAction:(input:ActionInput)=>void};
const fmt=(n:number)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(n);
function Country({code,name}:{code:string;name:string}){return <span className="traffic-country">{/^[A-Z]{2}$/.test(code)&&code!=='ZZ'?<img src={`https://flagcdn.com/w40/${code.toLowerCase()}.png`} alt={countryFlag(code)} width={24} height={16} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true;}}/>:<span aria-hidden>🌐</span>}{name==='(not set)'?'Bilinmeyen ülke':name||'Bilinmeyen ülke'} <small>{code==='(not set)'?'':code}</small></span>;}
export default function TrafficAnalytics({data,busy,result,onAction}:Props){
 const [period,setPeriod]=useState('week'),[country,setCountry]=useState(''),[source,setSource]=useState(''),[propertyId,setPropertyId]=useState(''),[disconnect,setDisconnect]=useState(false);
 if(!data)return <s-section><s-paragraph>Ziyaretçi raporlarını mağaza sahibi veya yetkilendirilmiş yönetici görüntüleyebilir.</s-paragraph></s-section>;
 const connection=data.connection,report=data.reports[period];
 const filtered=(r:{countryId:string;sessionSource:string})=>(!country||r.countryId===country)&&(!source||r.sessionSource===source);
 const productRows=report?.products.filter(filtered)||[],sourceRows=report?.sources.filter(filtered)||[];
 const countryRows=report?.countries.filter(r=>!country||country===r.countryId)||[];
 return <div className="traffic-panel">
  <LiveVisitors busy={busy} onAction={onAction}/>
  <h2 className="traffic-history-heading">Geçmiş trafik · Google Analytics</h2>
  <section className="analytics-card traffic-intro"><div><h2>Ziyaretçiler nereden geliyor?</h2><p>Direct, arama, Instagram, TikTok, reklamlar ve diğer siteler. Ülkeler ve görüntülenen ürünler aynı raporda.</p></div><span className="traffic-chip">Google Analytics 4</span></section>
  <details className="studio-details" open={!connection.connected}><summary>Analytics bağlantısı ve otomatik güncelleme</summary><div className="traffic-settings">
   <p>{connection.connected?`${connection.name} · ${connection.property} · ${connection.measurementId}`:'Önce nosweatusa.com sitesinin GA4 hesabını bağlayın. Search Console bağlantısı ziyaretçi verisi içermez.'}</p>
   <div className="traffic-actions"><s-button disabled={busy||!connection.configured} onClick={()=>onAction({intent:'traffic-connect'})}>{connection.connected?'Google hesabını yeniden bağla':'Google Analytics’i bağla'}</s-button><s-button disabled={busy} onClick={()=>onAction({intent:'refresh'})}>Bağlantıyı kontrol et</s-button></div>
   {result?.connectURL&&result.connectURL.includes('/google/analytics-connect?')&&<p><a href={result.connectURL} target="_blank" rel="noreferrer">Google Analytics iznini yeni pencerede aç →</a></p>}
   {connection.properties.length>1&&<label>Analytics mülkü<select value={connection.property} disabled={busy} onChange={e=>onAction({intent:'traffic-property',property:e.target.value})}>{connection.properties.map(p=><option key={p.property} value={p.property}>{p.name}</option>)}</select></label>}
   {connection.connected&&<label className="traffic-check"><input type="checkbox" checked={data.auto} disabled={busy} onChange={e=>onAction({intent:'traffic-settings',auto:String(e.target.checked)})}/> Son 7 gün raporunu her gün otomatik yenile</label>}
   {connection.serviceEmail&&<details><summary>Hizmet hesabıyla bağlan</summary><p>GA4 mülkünde bu hesaba Görüntüleyici erişimi verin: <strong>{connection.serviceEmail}</strong></p><label>GA4 sayısal mülk kimliği<input inputMode="numeric" value={propertyId} onChange={e=>setPropertyId(e.target.value)} placeholder="Örnek: 123456789"/></label><s-button disabled={busy||!/^\d+$/.test(propertyId)} onClick={()=>onAction({intent:'traffic-service',propertyId})}>Erişimi doğrula ve bağla</s-button></details>}
   {connection.connected&&<div><s-button disabled={busy} onClick={()=>setDisconnect(!disconnect)}>Bağlantıyı kaldır</s-button>{disconnect&&<p>Analytics bağlantısı ve uygulamadaki ziyaret raporları silinecek. <s-button disabled={busy} onClick={()=>{onAction({intent:'traffic-disconnect',confirm:'DISCONNECT'});setDisconnect(false);}}>Kaldırmayı onayla</s-button></p>}</div>}
  </div></details>
  <section className="analytics-card"><div className="traffic-toolbar"><label>Dönem<select value={period} disabled={busy} onChange={e=>{setPeriod(e.target.value);setCountry('');setSource('');}}>{Object.entries(TRAFFIC_PERIODS).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><s-button disabled={busy||!connection.connected} variant="primary" onClick={()=>onAction({intent:'traffic-sync',period})}>{busy?'Getiriliyor…':'Verileri getir / yenile'}</s-button>{report&&<s-button disabled={busy} onClick={()=>onAction({intent:'traffic-pdf',period})}>PDF indir</s-button>}</div>
  <p>Yalnızca ölçülebilen ziyaretler gösterilir. İzin vermeyen ziyaretçiler ve engellenen ölçümler eksik olabilir. Direct, kaynağın belirlenemediği girişleri de içerir; reklam ayrımı için UTM veya bağlı reklam hesabı gerekir.</p></section>
  {!report?<section className="analytics-card"><h2>{connection.connected?'Bu dönem için rapor hazırlayın':'Analytics bağlantısı bekleniyor'}</h2><p>{connection.connected?'Verileri getir düğmesiyle gerçek ziyaret verilerini alın.':'Google hesabınızla bağlandıktan sonra geçmişte toplanmış veriler de gösterilebilir. Henüz toplanmayan ziyaretler geriye dönük oluşturulamaz.'}</p></section>:<>
   <p className="traffic-note">{report.start} — {report.end} · {report.timeZone} · Güncelleme: {new Date(report.generatedAt).toLocaleString('tr-TR')}</p>
   <s-banner tone="info">{report.partial?'Bugünün verisi henüz tamamlanmadı; tam önceki günle karşılaştırma geçicidir. ':'Son günlerin verisi işlendikçe değişebilir. '}Bu rapor gerçek zamanlı ziyaretçi listesi değildir.</s-banner>
   {Object.values(report.quality).some(Boolean)&&<s-banner tone="warning">{report.quality.limited?'Detaylar 10.000 satır sınırında kesildi. ':''}{report.quality.thresholded?'Google gizlilik eşiği uygulayabilir. ':''}{report.quality.sampled?'Google örneklenmiş veri döndürdü. ':''}{report.quality.otherRow?'Bazı detaylar Google tarafından (other) altında gruplandı. ':''}Detay tablolarının toplamı genel toplamla aynı olmayabilir.</s-banner>}
   <div className="traffic-metrics">{([{key:'sessions',label:'Ziyaret (oturum)'},{key:'totalUsers',label:'Ziyaretçi (GA4 kullanıcısı)'},{key:'screenPageViews',label:'Sayfa görüntüleme'}] as const).map(m=>{const current=report.current[m.key],previous=report.previous[m.key],diff=current-previous;return <section className="analytics-card" key={m.key}><span>{m.label}</span><strong>{fmt(current)}</strong><small>Önceki: {fmt(previous)} · Fark: {diff>0?'+':''}{fmt(diff)}{previous?` (${fmt(diff/previous*100)}%)`:''}</small></section>;})}</div>
   <p className="traffic-note">Önceki dönem: {report.previousStart} — {report.previousEnd}. Üstteki toplamlar tüm siteye aittir. Kullanıcılar satırlar arasında tekrar edebilir; satır kullanıcı sayıları toplanmaz.</p>
   <section className="analytics-card"><h2>Günlük ziyaretler</h2><div className="traffic-chart">{report.daily.map(d=><div key={d.date}><time>{`${d.date.slice(6,8)}.${d.date.slice(4,6)}`}</time><div><span style={{width:`${Math.max(1,d.sessions/Math.max(1,...report.daily.map(r=>r.sessions))*100)}%`}}/></div><strong>{fmt(d.sessions)}</strong></div>)}</div>{!report.daily.length&&<p>Bu dönemde ölçülmüş ziyaret yok.</p>}</section>
   <section className="analytics-card"><h2>Detayları incele</h2><div className="traffic-toolbar"><label>Ülke<select value={country} onChange={e=>setCountry(e.target.value)}><option value="">Tüm ülkeler</option>{report.countries.map(c=><option key={c.countryId} value={c.countryId}>{c.country} ({c.countryId})</option>)}</select></label><label>Trafik kaynağı<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Tüm kaynaklar</option>{[...new Set(report.sources.map(s=>s.sessionSource))].sort().map(s=><option value={s} key={s}>{s}</option>)}</select></label></div><p>Filtreler aşağıdaki kaynak ve ürün detaylarına uygulanır. Ülke özeti tüm kaynakları kapsar.</p></section>
   <section className="analytics-card"><h2>Kaynak, kampanya ve ülke</h2><div className="traffic-table"><table><thead><tr><th>Kaynak</th><th>Tür / kampanya</th><th>Ülke</th><th>Ziyaret</th><th>Kullanıcı</th></tr></thead><tbody>{sourceRows.slice(0,200).map((s,i)=><tr key={i}><td><strong>{s.label}</strong><small>{s.sessionSource} / {s.sessionMedium}</small></td><td>{s.sessionDefaultChannelGroup}<small>{s.sessionCampaignName}</small></td><td><Country code={s.countryId} name={s.country}/></td><td>{fmt(s.sessions)}</td><td>{fmt(s.totalUsers)}</td></tr>)}</tbody></table></div><p>{sourceRows.length?`İlk ${Math.min(200,sourceRows.length)} / ${sourceRows.length} satır gösteriliyor.`:'Bu filtrede ölçülmüş trafik bulunamadı.'}</p></section>
   <section className="analytics-card"><h2>Ülkeler · Tüm kaynaklar</h2><div className="traffic-countries">{countryRows.map(c=><button key={c.countryId} onClick={()=>setCountry(country===c.countryId?'':c.countryId)} aria-pressed={country===c.countryId}><Country code={c.countryId} name={c.country}/><strong>{fmt(c.sessions)} ziyaret</strong><small>{fmt(c.totalUsers)} kullanıcı</small></button>)}</div>{!countryRows.length&&<p>Ülke verisi yok.</p>}</section>
   <section className="analytics-card"><h2>Hangi ürünlere bakıldı?</h2><p>Ürün sayfası görüntülemeleri; aynı kişinin tekrar görüntülemeleri dahildir. Kaynak, o ziyaretin GA4 oturum kaynağıdır.</p><div className="traffic-table"><table><thead><tr><th>Ürün</th><th>Kaynak / kampanya</th><th>Ülke</th><th>Görüntüleme</th></tr></thead><tbody>{productRows.slice(0,200).map((p,i)=><tr key={i}><td><div className="traffic-product">{p.image&&<img src={p.image} alt="" width={44} height={44} loading="lazy"/>}<div><strong>{p.title}</strong><small>{p.path}</small></div></div></td><td>{p.label}<small>{p.sessionMedium} · {p.sessionCampaignName}</small></td><td><Country code={p.countryId} name={p.country}/></td><td>{fmt(p.screenPageViews)}</td></tr>)}</tbody></table></div><p>{productRows.length?`İlk ${Math.min(200,productRows.length)} / ${productRows.length} satır gösteriliyor.`:'Bu dönemde/filtrede ölçülmüş ürün sayfası görüntülemesi bulunamadı.'}</p></section>
  </>}
 </div>;
}
