import {useState} from 'react';
import type {ActionInput} from '../lib/types';
export type BotData={total:number;pixel:number;serverLogs:number;limited:boolean;groups:{family:string;source:string;count:number}[];recent:{family:string;source:string;path:string;country:string;at:string}[]};
export default function VisitorBots({data,busy,onAction}:{data?:BotData;busy:boolean;onAction:(input:ActionInput)=>void}){
 const [logs,setLogs]=useState(''),[error,setError]=useState('');
 return <section className="analytics-card visitor-bots"><div className="traffic-intro"><div><h3>Bot ve tarayıcı robotları</h3><p>Seçili dönem · İnsan ziyaretlerinden ayrı tutulur.</p></div><span className="traffic-chip">{data?.total||0} bot olayı</span></div>
  <p><strong>Sunucu günlükleri otomatik bağlı değil.</strong> Shopify mağazasına gelip JavaScript çalıştırmayan botlar piksel tarafından görülemez. Bu bölüm yalnızca piksele ulaşan bot işaretlerini ve yüklediğiniz sunucu günlüklerini kapsar.</p>
  <div className="bot-counts"><span>Pikselde yakalanan: <b>{data?.pixel||0}</b></span><span>Sunucu günlüğünden: <b>{data?.serverLogs||0}</b></span></div>
  {data?.limited&&<p>En son 10.000 bot kaydı kullanılıyor; dönem toplamı eksik olabilir.</p>}
  {data?.groups.length?<div className="traffic-table"><table><thead><tr><th>Bot işareti</th><th>Veri kaynağı</th><th>Olay</th></tr></thead><tbody>{data.groups.map(g=><tr key={g.family+g.source}><td>{g.family}</td><td>{g.source==='pixel'?'Piksel':'Yüklenen sunucu günlüğü'}</td><td>{g.count}</td></tr>)}</tbody></table></div>:<p>Bu dönemde ölçülmüş bot kaydı yok. Bu, mağazaya hiç bot gelmediği anlamına gelmez.</p>}
  {!!data?.recent.length&&<details className="studio-details"><summary>Son bot istekleri</summary><ul>{data.recent.map((e,i)=><li key={i}>{e.at.replace('T',' ').slice(0,16)} UTC · {e.family} · {e.path} · {e.country}</li>)}</ul></details>}
  <details className="studio-details"><summary>Sunucu günlüğü yükle (isteğe bağlı)</summary><div className="traffic-settings"><p>Bir sunucu/CDN günlük dosyanız varsa JSON listesi yükleyebilirsiniz. Son 30 gün, en fazla 1.000 satır / 250 KB. IP ve ham kullanıcı aracısı saklanmaz; kişisel alanları dosyadan çıkarın.</p><pre>{'[{"timestamp":"ISO-8601 UTC", "path":"/products/urun", "user_agent":"Googlebot", "country":"US", "request_id":"benzersiz-id"}]'}</pre><p>request_id aynı isteğin tekrar yüklenmesini önler. Eksikse aynı zaman, sayfa ve bot işaretindeki kayıtlar birleştirilir. Ülke isteğe bağlıdır.</p><label>Bot günlüğü (JSON)<input type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];setLogs('');setError('');if(!file)return;if(file.size>250000){setError('Dosya en fazla 250 KB olabilir.');return;}try{const text=await file.text();const rows=JSON.parse(text);if(!Array.isArray(rows)||rows.length>1000)throw Error('En fazla 1.000 satırlık JSON listesi seçin.');setLogs(text);}catch{setError('Geçerli bir JSON listesi seçin (en fazla 1.000 satır).');}}}/></label>{error&&<p role="alert">{error}</p>}<s-button disabled={busy||!logs} onClick={()=>{onAction({intent:'visitors-import-bots',logs});setLogs('');}}>Bot kayıtlarını içe aktar</s-button></div></details>
  <small>Bot adı User-Agent işaretine dayanır; doğrulanmış kimlik değildir. Taklit edilebilir. Sayılar tekil bot sayısı değil, kaydedilen olay/istek sayısıdır.</small>
 </section>;
}
