import {build} from 'esbuild';
import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createServer} from 'node:http';
import assert from 'node:assert/strict';
import {initialWorkspace,dashboardData} from '../app/lib/workspace.server.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH||'playwright');
const dir=await mkdtemp(join(tmpdir(),'nosweat-ui-'));
const state=initialWorkspace('preview.myshopify.com');
state.catalog.pages=[{id:'p1',type:'product',title:'Preview product',handle:'preview',descriptionHtml:'<p>Example product description for interface verification.</p>',seo:{title:'',description:''},images:[{id:'gid://shopify/MediaImage/1',url:'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="100" height="100"%3E%3Crect width="100" height="100" fill="lightgray"/%3E%3C/svg%3E',altText:''}],url:'https://nosweatusa.com/products/preview'}];
state.gsc=[{source:'google-api',country:'usa',device:'all',searchType:'web',property:'sc-domain:nosweatusa.com',grain:'page',startDate:'2026-08-01',endDate:'2026-08-28',importedAt:new Date().toISOString(),rows:[{page:state.catalog.pages[0].url,clicks:10,impressions:1000,position:8}]}];
state.growth.reports=[{...state.gsc[0],grain:'page-query',rows:[{...state.gsc[0].rows[0],query:'example product'}]}];
state.backlinks=[{id:'b1',url:'https://example.org/article',status:'mention',links:[],checkedAt:null,note:'Sample unlinked mention'}];
const data={...dashboardData(state),canWrite:true,canWriteFiles:true,compressionConfigured:true,canManageGoogle:true,google:{configured:true,connected:false,properties:[],property:'',autoSync:false,syncedAt:null},compressions:[]};
await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import Dashboard from './app/components/SeoDashboard';window.actions=[];createRoot(document.getElementById('root')).render(<Dashboard data={${JSON.stringify(data)}} busy={false} onAction={a=>window.actions.push(a)}/>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,outfile:join(dir,'app.js'),jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'}});
const html='<!doctype html><html lang="az"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script src="https://cdn.shopify.com/shopifycloud/polaris.js"></script><link rel="stylesheet" href="/app.css"><body><div style="padding:12px;background:#fff3cd">Sınaq önizləməsi — nümunə məlumatları, Shopify bağlantısı yoxdur</div><div id="root"></div><script src="/app.js"></script></body></html>';
const server=createServer(async(req,res)=>{try{const name=req.url==='/app.js'?'app.js':req.url==='/app.css'?'app.css':null;res.setHeader('content-type',name?.endsWith('js')?'text/javascript':name?'text/css':'text/html');res.end(name?await readFile(join(dir,name)):html);}catch{res.statusCode=404;res.end();}});
await new Promise((yes,no)=>{server.once('error',no);server.listen(0,'127.0.0.1',yes);});
let browser;
try{
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1360,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'networkidle'});
 await page.waitForFunction(()=>customElements.get('s-page')&&customElements.get('s-text-field'));
 await page.getByRole('button',{name:'Hədəf olaraq seç',exact:true}).click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).keyword,'example product');
 await page.getByRole('combobox',{name:'ABŞ-a çatdırılma qiyməti və müddəti aydın göstərilir',exact:true}).selectOption('yes');assert.equal((await page.evaluate(()=>window.actions)).at(-1).intent,'growth-check');
 await page.getByRole('button',{name:'Tamamladım',exact:true}).first().click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).intent,'growth-task');
 await page.getByRole('combobox',{name:'Xarici mənbə',exact:true}).selectOption('b1');await page.getByRole('combobox',{name:'Təklif ediləcək məhsul / kolleksiya',exact:true}).selectOption('p1');await page.getByRole('button',{name:'İngiliscə layihə hazırla',exact:true}).click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).intent,'growth-outreach');
 await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/growth-desktop-preview.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/growth-mobile-preview.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Growth mobile overflow');await page.setViewportSize({width:1360,height:1000});
 await page.getByRole('button',{name:'Mətni düzəlt',exact:true}).click();await page.getByRole('textbox',{name:'SEO başlığı',exact:true}).waitFor();
 await page.getByRole('button',{name:'Səhifələr',exact:true}).click();
 await page.getByRole('button',{name:'İncələ',exact:true}).click();
 await page.getByRole('textbox',{name:'SEO başlığı',exact:true}).fill('Reviewed browser title');
 await page.getByRole('textbox',{name:'Meta təsvir',exact:true}).fill('Reviewed browser description');
 await page.getByRole('button',{name:'Layihəni saxla',exact:true}).click();
 const actions=await page.evaluate(()=>window.actions);assert.equal(actions.at(-1).title,'Reviewed browser title');assert.equal(actions.at(-1).description,'Reviewed browser description');
 await page.getByRole('button',{name:'Şəkillər',exact:true}).click();await page.getByRole('textbox',{name:'Şəkildə görünəni dəqiq təsvir et'}).fill('Product bag in browser test');await page.getByRole('button',{name:'Layihəni saxla',exact:true}).click();
 assert.equal((await page.evaluate(()=>window.actions)).at(-1).alt,'Product bag in browser test');
 await page.getByRole('button',{name:'Texniki SEO',exact:true}).click();await page.getByRole('button',{name:'Texniki yoxlamanı başlat',exact:true}).click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).intent,'technical');
 await page.getByRole('button',{name:'Şəkil sıxılması',exact:true}).click();
 await page.getByRole('combobox',{name:'Sıxılacaq məhsul şəkli'}).selectOption('gid://shopify/MediaImage/1');
 await page.getByRole('button',{name:'Sıxılmış önizləmə hazırla'}).click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).intent,'compression-prepare');
 await page.getByRole('button',{name:'Backlinklər',exact:true}).click();await page.getByRole('textbox',{name:'Xarici mənbə səhifəsi'}).fill('https://example.com/article');await page.getByRole('button',{name:'İzləməyə əlavə et'}).click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).url,'https://example.com/article');
 await page.getByRole('button',{name:'Google nəticələri',exact:true}).click();await page.getByRole('button',{name:'Google bağlantısını başlat'}).click();assert.equal((await page.evaluate(()=>window.actions)).at(-1).intent,'google-connect');
 await page.getByRole('button',{name:'Ümumi baxış',exact:true}).click();await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/desktop-preview.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile-preview.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Mobile horizontal overflow');assert.deepEqual(errors,[]);
 console.log('Browser passed: text input, image draft, navigation, technical action, compression selection, backlink input, Google connect action, desktop/mobile, no page errors.');
}finally{await browser?.close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
