import { readFile, mkdir, writeFile } from 'node:fs/promises';

// Keep the local SQLite model definitions as the single source of truth.
const source = await readFile(new URL('../prisma/schema.prisma', import.meta.url), 'utf8');
const schema = '// Generated by scripts/postgres-schema.mjs. Do not edit directly.\n' + source
  .replace('provider = "prisma-client-js"', 'provider = "prisma-client-js"\n  output = "../../node_modules/@nosweat/postgres-client"\n  binaryTargets = ["native", "rhel-openssl-3.0.x"]')
  .replace('provider = "sqlite"', 'provider = "postgresql"')
  .replace('url      = env("DATABASE_URL")', 'url      = env("DATABASE_URL")\n  directUrl = env("DIRECT_URL")');
await mkdir(new URL('../prisma/postgresql/', import.meta.url), { recursive: true });
await writeFile(new URL('../prisma/postgresql/schema.prisma', import.meta.url), schema);
