export type SEO = {title:string;description:string};
export type Issue = {code:string;severity:'high'|'medium'|'low';label:string;detail:string};
export type Image = {id?:string;url:string;altText:string};
export type ImageDraft = {imageId:string;url:string;before:string;after:string};
export type Page = {id:string;type:'product'|'collection';title:string;handle:string;url:string;seo:SEO;descriptionHtml:string;status:string;score:number;issues:Issue[];keyword:string;images:Image[];imagesTruncated?:boolean;suggestion:SEO & {note:string}};
export type Draft = {pageId:string;pageTitle:string;before:SEO;beforeHash:string;after:SEO;afterHash:string;stale:boolean;updatedAt:string};
export type LinkSuggestion = {fromId:string;fromTitle:string;toId:string;toTitle:string;toUrl:string;anchor:string;common:string[]};
export type GoogleRow = {page:string;query:string;clicks:number;impressions:number;ctr:number;position:number};
export type GoogleReport = {startDate:string;endDate:string;property:string;grain:string;note:string;rows:GoogleRow[];opportunities:GoogleRow[];totals:{clicks:number;impressions:number;ctr:number;position:number|null};comparison:{startDate:string;endDate:string;previous:{clicks:number;impressions:number;ctr:number;position:number|null}}|null};
export type Change = {id:string;pageId:string;pageTitle:string;before:SEO;after:SEO;status:string;createdAt:string};
export type TechnicalReport = {checkedAt:string;warnings:string[];pages:{pageId:string;title:string;url:string;status:number|null;error?:string;technical:{h1Count:number;canonical:string;noindex:boolean;schemaTypes:string[];invalidSchema:number}|null}[];links:{url:string;status:number|null;broken:boolean;error?:string;sources:string[]}[];infrastructure:{name:string;status:number|null;valid:boolean}[]};
export type GoogleConnection = {configured:boolean;connected:boolean;properties:string[];property:string;autoSync:boolean;syncedAt:string|null};
export type Compression = {id:string;imageId:string;status:string;beforeBytes:number;afterBytes:number;afterHash:string;originalURL:string;optimizedURL:string};
export type Backlink = {id:string;url:string;status:string;links:{url:string;anchor:string;rel:string}[];checkedAt:string|null;note:string};
export type GrowthMetric={clicks:number;impressions:number;ctr:number;position:number|null};
export type GrowthTask={id:string;title:string;detail:string;pageId:string|null;section:string;priority:number};
export type GrowthCheck={key:string;label:string;status:string;automatic:boolean;updatedAt:string|null};
export type GrowthEffect={id:string;pageId:string;pageTitle:string;changed:string;beforeStart:string;beforeEnd:string;afterStart:string;afterEnd:string;before:GrowthMetric|null;after:GrowthMetric|null;clickDifference:number|null;status:string;reason:string};
export type GrowthData={week:string;syncedAt:string|null;current:{startDate:string;endDate:string;property:string;truncated:boolean;totals:GrowthMetric}|null;previous:{startDate:string;endDate:string;property:string;truncated:boolean;totals:GrowthMetric}|null;opportunities:(GrowthMetric&{pageId:string;pageTitle:string;url:string;previous:GrowthMetric|null;reason:string;action:string})[];queries:(GoogleRow&{pageId:string;pageTitle:string;pageCount:number;mapped:boolean})[];queryCount:number;queryLimited:boolean;products:{pageId:string;pageTitle:string;url:string;checks:GrowthCheck[]}[];tasks:GrowthTask[];completed:GrowthTask[];effects:GrowthEffect[];outreach:{backlinkId:string;pageId:string;target:string;subject:string;body:string;updatedAt:string}[];warnings:string[]};
export type Dashboard = {growth?:GrowthData;google?:GoogleConnection;compressions?:Compression[];compressionConfigured?:boolean;canManageGoogle?:boolean;backlinks?:Backlink[];backlinksAuto?:boolean;opportunities?:{query:string;url:string}[];catalog:{shop:{name:string;domain:string;adminDomain:string};pages:Page[];syncedAt:string|null;warnings:string[]};drafts:Draft[];imageDrafts:ImageDraft[];technical:TechnicalReport|null;mappings:Record<string,string>;links:LinkSuggestion[];gsc:GoogleReport|null;changes:Change[];snapshots:{date:string;pageCount:number;score:number|null;issues:number}[];canWrite:boolean;canWriteFiles:boolean};
export type ActionInput = Record<string,string> & {intent:string};
export type ActionResult = {ok?:boolean;message?:string;error?:string;download?:string;filename?:string;connectURL?:string};

import {useState} from 'react';

type Props={data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void;onEdit:(id:string)=>void;onNavigate:(section:string)=>void};
const fmt=(n:number)=>new Intl.NumberFormat('az-AZ').format(n);
const percent=(n:number)=>`${(n*100).toFixed(2)}%`;
function MetricLine({value}:{value:GrowthMetric}){return <s-paragraph>{fmt(value.clicks)} klik · {fmt(value.impressions)} görünmə · {percent(value.ctr)} CTR · {value.position?.toFixed(1)||'—'} orta mövqe</s-paragraph>;}
function OutreachEditor({data,busy,onAction}:Pick<Props,'data'|'busy'|'onAction'>){
 const [source,setSource]=useState(''),[pageId,setPageId]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[note,setNote]=useState('');
 const drafts=data.growth?.outreach||[];const backlink=data.backlinks?.find(b=>b.id===source);
 const selectSource=(id:string)=>{setSource(id);setNote('');const draft=drafts.find(d=>d.backlinkId===id);setPageId(draft?.pageId||'');setSubject(draft?.subject||'');setBody(draft?.body||'');};
 return <s-section heading="Backlink üçün əlaqə layihəsi"><s-stack direction="block" gap="base"><s-paragraph>İzlədiyin mənbə və uyğun məhsulu seç. İngiliscə mətn layihəsi hazırlayıb redaktə edə bilərsən. Göndərmə avtomatlaşdırılmır.</s-paragraph><s-select label="Xarici mənbə" value={source} onChange={e=>selectSource(e.currentTarget.value)}><s-option value="">Mənbə seç</s-option>{(data.backlinks||[]).map(b=><s-option key={b.id} value={b.id}>{b.url}{b.status==='mention'?' · linksiz qeyd':''}</s-option>)}</s-select><s-select label="Təklif ediləcək məhsul / kolleksiya" value={pageId} onChange={e=>setPageId(e.currentTarget.value)}><s-option value="">Səhifə seç</s-option>{data.catalog.pages.filter(p=>p.url).map(p=><s-option key={p.id} value={p.id}>{p.title}</s-option>)}</s-select><s-button disabled={busy||!backlink||!pageId} onClick={()=>onAction({intent:'growth-outreach',backlinkId:source,pageId})}>İngiliscə layihə hazırla</s-button>
 {drafts.find(d=>d.backlinkId===source)&&<s-button disabled={busy} onClick={()=>{const d=drafts.find(d=>d.backlinkId===source)!;setSubject(d.subject);setBody(d.body);setPageId(d.pageId);}}>Saxlanmış layihəni redaktəyə aç</s-button>}
 <s-text-field label="Məktubun mövzusu" value={subject} maxLength={200} onInput={e=>setSubject(e.currentTarget.value)}/><s-text-area label="Əlaqə mətni" rows={8} value={body} maxLength={5000} onInput={e=>setBody(e.currentTarget.value)}/><s-stack direction="inline" gap="base"><s-button disabled={busy||!source||!pageId||!subject||!body} onClick={()=>onAction({intent:'growth-outreach',backlinkId:source,pageId,subject,body})}>Redaktə edilmiş mətni saxla</s-button><s-button disabled={!body} onClick={async()=>{try{await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);setNote('Mətn kopyalandı.');}catch{setNote('Brauzer kopyalamağa icazə vermədi. Mətni sahədən seçib kopyala.');}}}>Mətni kopyala</s-button></s-stack>{note&&<s-banner tone="info">{note}</s-banner>}
 {drafts.length>0&&<s-paragraph color="subdued">{drafts.length} saxlanmış layihə var. Mənbə seçib layihəni redaktəyə aç. Məktubun ünvanını və məzmuna uyğunluğunu özün yoxla.</s-paragraph>}</s-stack></s-section>;
}
export default function GrowthPanel({data,busy,onAction,onEdit,onNavigate}:Props){
 const g=data.growth;const [focus,setFocus]=useState(''),[queryFilter,setQueryFilter]=useState('');if(!g)return null;
 const runTask=(t:GrowthTask)=>{if(t.section==='editor'&&t.pageId)onEdit(t.pageId);else if(t.section==='sync')onAction({intent:'sync'});else if(t.section==='checklist'){setFocus(t.pageId||'');document.getElementById('growth-checklist')?.scrollIntoView({behavior:'smooth'});}else if(t.section==='outreach')document.getElementById('growth-outreach')?.scrollIntoView({behavior:'smooth'});else onNavigate(t.section);};
 const product=g.products.find(p=>p.pageId===(focus||g.products[0]?.pageId));
 const queries=g.queries.filter(q=>(!focus||q.pageId===focus)&&`${q.query} ${q.pageTitle}`.toLowerCase().includes(queryFilter.toLowerCase()));
 return <s-stack direction="block" gap="base"><s-section heading="ABŞ-dan müştəri qazanmaq"><s-stack direction="block" gap="base"><s-paragraph>ABŞ · Google Web axtarışı · bütün cihazlar. Əvvəlcə uyğun ziyarətçi gətirəcək işləri seç, sonra nəticələri izlə.</s-paragraph><s-stack direction="inline" gap="base"><s-button variant="primary" disabled={busy||!data.google?.connected} onClick={()=>onAction({intent:'google-sync'})}>ABŞ məlumatlarını yenilə</s-button><s-button onClick={()=>onNavigate('Google nəticələri')}>Google bağlantısını aç</s-button></s-stack>{!g.current?<s-banner tone="info">ABŞ üzrə real hesabat yoxdur. Google hesabını qoşub məlumatları gətir. Kataloq yoxlamalarını indi də tamamlaya bilərsən.</s-banner>:<><s-paragraph>{g.current.startDate} — {g.current.endDate} · {g.current.property}</s-paragraph><MetricLine value={g.current.totals}/>{g.previous&&<s-paragraph color="subdued">Əvvəlki {g.previous.startDate} — {g.previous.endDate}: {fmt(g.previous.totals.clicks)} klik, {fmt(g.previous.totals.impressions)} görünmə. Klik fərqi: {fmt(g.current.totals.clicks-g.previous.totals.clicks)}.</s-paragraph>}<s-paragraph color="subdued">Mövqe dövr üzrə ortadır. Cəmlər Google-un qaytardığı səhifə sətirlərinə aiddir; bütün trafik və satışları göstərmir.</s-paragraph></>}{g.warnings.map(w=><s-banner key={w} tone="warning">{w}</s-banner>)}</s-stack></s-section>
 <s-section heading="Bu həftənin 3 əsas işi"><s-paragraph color="subdued">Həftə: {g.week}. Sıralama müşahidə olunan problemlərə və görünmələrə əsaslanır. Tamamlanmış işin yerinə növbəti prioritet gəlir.</s-paragraph>{g.tasks.length?g.tasks.map(t=><div key={t.id} className="seo-growth-task"><div><s-heading>{t.title}</s-heading><s-paragraph>{t.detail}</s-paragraph></div><s-stack direction="inline" gap="base"><s-button disabled={busy} onClick={()=>runTask(t)}>İşə keç</s-button><s-button disabled={busy} onClick={()=>onAction({intent:'growth-task',taskId:t.id,done:'true'})}>Tamamladım</s-button></s-stack></div>):<s-paragraph>Hazırkı məlumatlarda açıq prioritet yoxdur. Bu, bütün SEO-nun tamamlandığını göstərmir.</s-paragraph>}{g.completed.map(t=><div className="seo-growth-task" key={t.id}><s-text>{t.title} — tamamlanmış kimi qeyd edilib</s-text><s-button disabled={busy} onClick={()=>onAction({intent:'growth-task',taskId:t.id,done:'false'})}>Yenidən aç</s-button></div>)}</s-section>
 <s-section heading="Klik artırma imkanları"><s-paragraph color="subdued">Seçim: 100+ görünmə, 3–20 orta mövqe və 3%-dən aşağı CTR. Bunlar redaktə üçün başlanğıc filtrləridir. Aşağı CTR-nin səbəbi təkcə başlıq olmaya bilər.</s-paragraph>{g.opportunities.length?<s-table><s-table-header-row><s-table-header>Məhsul / kolleksiya</s-table-header><s-table-header>Görünmə</s-table-header><s-table-header>Klik</s-table-header><s-table-header>CTR</s-table-header><s-table-header>Orta mövqe</s-table-header><s-table-header>Əməliyyat</s-table-header></s-table-header-row><s-table-body>{g.opportunities.map(o=><s-table-row key={o.pageId}><s-table-cell>{o.pageTitle}</s-table-cell><s-table-cell>{fmt(o.impressions)}</s-table-cell><s-table-cell>{fmt(o.clicks)}</s-table-cell><s-table-cell>{percent(o.ctr)}</s-table-cell><s-table-cell>{o.position?.toFixed(1)}</s-table-cell><s-table-cell><s-stack direction="inline" gap="small"><s-button disabled={busy} onClick={()=>onEdit(o.pageId)}>Mətni düzəlt</s-button><s-button onClick={()=>{setFocus(o.pageId);document.getElementById('growth-queries')?.scrollIntoView({behavior:'smooth'});}}>Axtarış ifadələrini göstər</s-button></s-stack></s-table-cell></s-table-row>)}</s-table-body></s-table>:<s-paragraph>{g.current?'Bu filtrlərə uyğun səhifə tapılmadı.':'Google məlumatı gələndən sonra imkanlar burada görünəcək.'}</s-paragraph>}</s-section>
 <div id="growth-queries"><s-section heading="Açar söz → məhsul uyğunluğu"><s-paragraph color="subdued">Google-un həqiqətən göstərdiyi sorğu–səhifə cütləridir. İfadənin məhsula uyğunluğunu yoxlayıb hədəf olaraq seç. Eyni ifadənin bir neçə səhifədə görünməsi avtomatik problem demək deyil.</s-paragraph><s-search-field label="ABŞ axtarış ifadəsi" value={queryFilter} onInput={e=>setQueryFilter(e.currentTarget.value)}/>{focus&&<s-button onClick={()=>setFocus('')}>Bütün məhsulların ifadələrini göstər</s-button>}<s-paragraph color="subdued">İlk {g.queries.length} / {g.queryCount} uyğun sətir. Gizlədilmiş sorğular və API limitləri səbəbindən tam siyahı deyil.</s-paragraph>{queries.length?<s-table><s-table-header-row><s-table-header>Axtarış ifadəsi</s-table-header><s-table-header>Səhifə</s-table-header><s-table-header>Görünmə / klik</s-table-header><s-table-header>Orta mövqe</s-table-header><s-table-header>Əməliyyat</s-table-header></s-table-header-row><s-table-body>{queries.map(q=><s-table-row key={`${q.pageId}-${q.query}`}><s-table-cell>{q.query}{q.pageCount>1&&<s-badge tone="info">{q.pageCount} səhifədədir</s-badge>}</s-table-cell><s-table-cell>{q.pageTitle}</s-table-cell><s-table-cell>{fmt(q.impressions)} / {fmt(q.clicks)}</s-table-cell><s-table-cell>{q.position?.toFixed(1)||'—'}</s-table-cell><s-table-cell><s-button disabled={busy||q.mapped||q.query.length>150} onClick={()=>onAction({intent:'keyword',pageId:q.pageId,keyword:q.query})}>{q.mapped?'Hədəf seçilib':'Hədəf olaraq seç'}</s-button></s-table-cell></s-table-row>)}</s-table-body></s-table>:<s-paragraph>Bu seçim üçün sorğu–səhifə məlumatı yoxdur.</s-paragraph>}</s-section></div>
 <div id="growth-checklist"><s-section heading="Məhsulun alışa hazırlığı"><s-select label="Yoxlanacaq məhsul" value={product?.pageId||''} onChange={e=>setFocus(e.currentTarget.value)}>{g.products.map(p=><s-option key={p.pageId} value={p.pageId}>{p.pageTitle}</s-option>)}</s-select>{product?<><s-paragraph color="subdued">Şəkil və təsvirin mövcudluğu kataloqdan yoxlanır. Keyfiyyət və qalan maddələr sənin əl ilə yoxlamandır; avtomatik uğurlu sayılmır.</s-paragraph>{product.checks.map(c=><div key={c.key} className="seo-growth-check"><div><s-text>{c.label}</s-text><div><s-text color="subdued">{c.automatic?'Kataloq məlumatı':c.updatedAt?`Əl ilə yoxlanıb: ${new Date(c.updatedAt).toLocaleDateString('az-AZ')}`:'Əl ilə yoxlama tələb olunur'}</s-text></div></div>{c.automatic?<s-badge tone={c.status==='yes'?'success':'warning'}>{c.status==='yes'?'Var':'Yoxdur'}</s-badge>:<s-select label={c.label} labelAccessibilityVisibility="exclusive" value={c.status} disabled={busy} onChange={e=>onAction({intent:'growth-check',pageId:product.pageId,check:c.key,status:e.currentTarget.value})}><s-option value="unknown">Yoxlanmayıb</s-option><s-option value="yes">Yoxladım, uyğundur</s-option><s-option value="no">Düzəliş lazımdır</s-option></s-select>}</div>)}{product.url&&<s-link href={product.url} target="_blank">Məhsulu canlı mağazada yoxla</s-link>}</>:<s-paragraph>Əvvəlcə məhsul kataloqunu gətir.</s-paragraph>}</s-section></div>
 <div id="growth-outreach"><OutreachEditor data={data} busy={busy} onAction={onAction}/></div>
 <s-section heading="Dəyişiklikdən sonrakı nəticələr"><s-paragraph color="subdued">Bu tətbiqdə qeydə alınmış SEO düzəlişinin əvvəlində və sonrasında 7 günlük ABŞ göstəriciləri müqayisə olunur. Dəyişiklik günü sayılmır. Mövsüm, qiymət, rəqabət və başqa dəyişikliklər nəticəyə təsir edə bilər.</s-paragraph>{g.effects.length?g.effects.map(e=><div className="seo-growth-effect" key={e.id}><s-heading>{e.pageTitle}</s-heading><s-paragraph>Dəyişiklik: {e.changed} · Pacific tarixilə</s-paragraph>{e.before&&e.after&&<div className="seo-comparison"><div><s-text>Əvvəl: {e.beforeStart} — {e.beforeEnd}</s-text><MetricLine value={e.before}/></div><div><s-text>Sonra: {e.afterStart} — {e.afterEnd}</s-text><MetricLine value={e.after}/><s-paragraph>Klik fərqi: {fmt(e.clickDifference||0)}</s-paragraph></div></div>}<s-paragraph color="subdued">{e.reason}</s-paragraph></div>):<s-paragraph>Hələ uyğun canlı SEO dəyişikliyi yoxdur. Təsdiqlənmiş düzəliş və kifayət qədər gündəlik Google məlumatı olduqda müqayisə görünəcək.</s-paragraph>}</s-section>
 </s-stack>;
}
