export type SEO = {title:string;description:string};
export type Issue = {code:string;severity:'high'|'medium'|'low';label:string;detail:string};
export type Image = {id?:string;url:string;altText:string};
export type ImageDraft = {imageId:string;url:string;before:string;after:string};
export type Page = {id:string;type:'product'|'collection';title:string;handle:string;url:string;seo:SEO;descriptionHtml:string;status:string;score:number;issues:Issue[];keyword:string;images:Image[];imagesTruncated?:boolean;suggestion:SEO & {note:string}};
export type Draft = {pageId:string;pageTitle:string;before:SEO;beforeHash:string;after:SEO;afterHash:string;stale:boolean;updatedAt:string};
export type LinkSuggestion = {fromId:string;fromTitle:string;toId:string;toTitle:string;toUrl:string;anchor:string;common:string[]};
export type GoogleRow = {page:string;query:string;clicks:number;impressions:number;ctr:number;position:number};
export type GoogleReport = {startDate:string;endDate:string;property:string;grain:string;note:string;rows:GoogleRow[];opportunities:GoogleRow[];totals:{clicks:number;impressions:number;ctr:number;position:number|null};comparison:{startDate:string;endDate:string;previous:{clicks:number;impressions:number;ctr:number;position:number|null}}|null};
export type Change = {id:string;pageId:string;pageTitle:string;before:SEO;after:SEO;status:string;createdAt:string};
export type TechnicalReport = {checkedAt:string;warnings:string[];pages:{pageId:string;title:string;url:string;status:number|null;error?:string;technical:{h1Count:number;canonical:string;noindex:boolean;schemaTypes:string[];invalidSchema:number}|null}[];links:{url:string;status:number|null;broken:boolean;error?:string;sources:string[]}[];infrastructure:{name:string;status:number|null;valid:boolean}[]};
export type GoogleConnection = {configured:boolean;connected:boolean;properties:string[];property:string;autoSync:boolean;syncedAt:string|null};
export type Compression = {id:string;imageId:string;status:string;beforeBytes:number;afterBytes:number;afterHash:string;originalURL:string;optimizedURL:string};
export type Backlink = {id:string;url:string;status:string;links:{url:string;anchor:string;rel:string}[];checkedAt:string|null;note:string};
export type Dashboard = {google?:GoogleConnection;compressions?:Compression[];compressionConfigured?:boolean;canManageGoogle?:boolean;backlinks?:Backlink[];backlinksAuto?:boolean;opportunities?:{query:string;url:string}[];catalog:{shop:{name:string;domain:string;adminDomain:string};pages:Page[];syncedAt:string|null;warnings:string[]};drafts:Draft[];imageDrafts:ImageDraft[];technical:TechnicalReport|null;mappings:Record<string,string>;links:LinkSuggestion[];gsc:GoogleReport|null;changes:Change[];snapshots:{date:string;pageCount:number;score:number|null;issues:number}[];canWrite:boolean;canWriteFiles:boolean};
export type ActionInput = Record<string,string> & {intent:string};
export type ActionResult = {ok?:boolean;message?:string;error?:string;download?:string;filename?:string;connectURL?:string};

import {useState} from 'react';

type Props={data:Dashboard;busy:boolean;onAction:(input:ActionInput)=>void;result?:ActionResult};
export function GoogleConnectionView({data,busy,onAction,result}:Props){
 const g=data.google;const [property,setProperty]=useState(g?.property||''),[auto,setAuto]=useState(g?.autoSync||false);
 if(!g)return null;
 return <s-section heading="Google Search Console bağlantısı"><s-stack direction="block" gap="base">
 {!g.configured&&<s-banner tone="info">Google girişi serverdə aktivləşdirilməlidir. Bu vaxt CSV idxalından istifadə edə bilərsən.</s-banner>}
 <s-paragraph>{g.connected?'Google hesabı bağlıdır. Hesabatlar birbaşa Search Console-dan gətirilir.':'Google hesabına oxuma icazəsi verərək CSV-siz hesabat al.'}</s-paragraph>
 <s-stack direction="inline" gap="base"><s-button disabled={busy||!g.configured||!data.canManageGoogle} onClick={()=>onAction({intent:'google-connect'})}>{g.connected?'Google hesabını yenidən qoş':'Google bağlantısını başlat'}</s-button><s-button disabled={busy} onClick={()=>onAction({intent:'refresh'})}>Bağlantı vəziyyətini yenilə</s-button></s-stack>
 {result?.connectURL&&<s-banner tone="info"><s-link href={result.connectURL} target="_blank">Google icazə səhifəsini aç</s-link><s-paragraph>Yeni pəncərədə girişi tamamla, sonra burada bağlantı vəziyyətini yenilə. Link 10 dəqiqə etibarlıdır.</s-paragraph></s-banner>}
 {g.connected&&<><s-select label="Search Console property" value={property||g.property} onChange={e=>setProperty(e.currentTarget.value)}>{g.properties.map(p=><s-option key={p} value={p}>{p}</s-option>)}</s-select><s-checkbox label="Gündəlik avtomatik yenilə" checked={auto} onChange={e=>setAuto(e.currentTarget.checked)}/><s-paragraph color="subdued">Avtomatik yeniləmə üçün serverin gündəlik tapşırığı işləməlidir. Son API yeniləməsi: {g.syncedAt?new Date(g.syncedAt).toLocaleString('az-AZ'):'Hələ yoxdur'}. Son 3 gün məlumatın tamamlanması üçün gözlənilir.</s-paragraph><s-stack direction="inline" gap="base"><s-button disabled={busy||!data.canManageGoogle} onClick={()=>onAction({intent:'google-settings',property:property||g.property,autoSync:String(auto)})}>Parametrləri saxla</s-button><s-button variant="primary" disabled={busy} onClick={()=>onAction({intent:'google-sync'})}>Google hesabatını gətir</s-button><s-button tone="critical" disabled={busy||!data.canManageGoogle} onClick={()=>onAction({intent:'google-disconnect'})}>Google bağlantısını ayır</s-button></s-stack></>}
 {!data.canManageGoogle&&<s-paragraph color="subdued">Google hesabını mağaza sahibi qoşmalıdır.</s-paragraph>}
 </s-stack></s-section>;
}
const size=(bytes:number)=>`${(bytes/1024).toFixed(1)} KB`;
export function CompressionView({data,busy,onAction}:Props){
 const [imageId,setImageId]=useState(''),[confirm,setConfirm]=useState(''),[remove,setRemove]=useState('');const images=new Map<string,{id:string;title:string}>();
 for(const p of data.catalog.pages)for(const image of p.images||[])if(image.id)images.set(image.id,{id:image.id,title:p.title});
 return <><s-section heading="Şəkil sıxılması"><s-stack direction="block" gap="base"><s-paragraph>Ölçülər qorunur. JPEG və WebP keyfiyyəti 82 ilə yenidən kodlaşdırılır; PNG itkisiz sıxılır. Fayl kiçilməzsə dəyişiklik hazırlanmır. Shopify da şəkilləri optimallaşdırdığı üçün mağazanın sürətində artım zəmanəti yoxdur.</s-paragraph>{!data.compressionConfigured&&<s-banner tone="info">Şəkil önizləmələri üçün serverin inteqrasiya açarı qurulmalıdır.</s-banner>}<s-select label="Sıxılacaq məhsul şəkli" value={imageId} onChange={e=>setImageId(e.currentTarget.value)}><s-option value="">Şəkil seç</s-option>{[...images.values()].map(i=><s-option key={i.id} value={i.id}>{i.title} · {i.id.split('/').pop()}</s-option>)}</s-select><s-button disabled={busy||!imageId||!data.compressionConfigured} onClick={()=>onAction({intent:'compression-prepare',imageId})}>Sıxılmış önizləmə hazırla</s-button><s-paragraph color="subdued">Maksimum 20 MB və 40 milyon piksel; animasiyalar daxil deyil. Bir anda 10 iş və onların orijinalları saxlanılır.</s-paragraph></s-stack></s-section>
 {(data.compressions||[]).map(c=><s-section key={c.id} heading={images.get(c.imageId)?.title||'Şəkil sıxılması'}><s-stack direction="block" gap="base"><s-paragraph>{size(c.beforeBytes)} → {size(c.afterBytes)} · Hazırlanan faylda {Math.round((1-c.afterBytes/c.beforeBytes)*100)}% azalma. Vəziyyət: {({draft:'Təsdiq gözləyir',submitted:'Shopify emalına göndərilib',unconfirmed:'Nəticəni yoxlamaq lazımdır',ready:'Shopify-da təsdiqlənib',failed:'Emal alınmadı'} as Record<string,string>)[c.status]||c.status}</s-paragraph><div className="seo-compression-preview"><div><s-heading>Orijinal</s-heading><img src={c.originalURL} alt="Sıxılmadan əvvəl məhsul" loading="lazy"/><s-link href={c.originalURL} target="_blank">Orijinal ehtiyat nüsxəni aç / endir</s-link></div><div><s-heading>Sıxılmış önizləmə</s-heading><img src={c.optimizedURL} alt="Sıxılmış məhsul önizləməsi" loading="lazy"/><s-link href={c.optimizedURL} target="_blank">Tam ölçüdə müqayisə et</s-link></div></div>
 <s-stack direction="inline" gap="base">{c.status==='draft'&&<s-button disabled={busy||!data.canWriteFiles} onClick={()=>setConfirm(c.id)}>Shopify-da tətbiq et</s-button>}{['submitted','unconfirmed','ready'].includes(c.status)&&<s-button disabled={busy} onClick={()=>onAction({intent:'compression-check',id:c.id})}>Emal vəziyyətini yoxla</s-button>}{!['submitted','unconfirmed'].includes(c.status)&&<s-button disabled={busy} tone="critical" onClick={()=>setRemove(c.id)}>İşi və ehtiyat nüsxəni sil</s-button>}</s-stack>
 {confirm===c.id&&<s-banner tone="warning"><s-paragraph>Bu faylın bütün istifadə yerlərində şəkil dəyişəcək. Hər iki tamölçülü şəkli müqayisə et. Orijinal burada saxlanacaq.</s-paragraph><s-button disabled={busy} variant="primary" onClick={()=>{onAction({intent:'compression-apply',id:c.id,afterHash:c.afterHash,confirm:'APPLY'});setConfirm('');}}>Təsdiqlə və faylı yenilə</s-button></s-banner>}
 {remove===c.id&&<s-banner tone="warning"><s-paragraph>Orijinal ehtiyat nüsxə də silinəcək. Lazımdırsa əvvəlcə onu endir. Shopify faylı bu əməliyyatla dəyişmir.</s-paragraph><s-button tone="critical" disabled={busy} onClick={()=>{onAction({intent:'compression-delete',id:c.id,confirm:'DELETE'});setRemove('');}}>Silməni təsdiqlə</s-button></s-banner>}
 </s-stack></s-section>)}</>;
}
export function BacklinksView({data,busy,onAction}:Props){const [url,setURL]=useState('');
 return <><s-section heading="Backlink imkanları və izləmə"><s-stack direction="block" gap="base"><s-paragraph>Xarici saytdakı mənbə səhifəsini əlavə et. Alət No Sweat USA-ya linki, link atributlarını və linksiz brend qeydini yoxlayır. Xarici saytda özü hesab və ya link yaratmır.</s-paragraph><s-url-field label="Xarici mənbə səhifəsi" value={url} onInput={e=>setURL(e.currentTarget.value)} placeholder="https://example.com/article"/><s-stack direction="inline" gap="base"><s-button disabled={busy||!url} onClick={()=>onAction({intent:'backlink-add',url})}>İzləməyə əlavə et</s-button><s-button disabled={busy||!data.backlinks?.length} onClick={()=>onAction({intent:'backlink-check'})}>Mənbələri yoxla</s-button></s-stack><s-checkbox label="Gündəlik avtomatik yoxla (server tapşırığı tələb olunur)" checked={data.backlinksAuto||false} disabled={busy} onChange={e=>onAction({intent:'backlink-auto',enabled:String(e.currentTarget.checked)})}/></s-stack></s-section>
 <s-section heading="İmkan axtarışı"><s-paragraph color="subdued">Bu sorğular axtarış üçün hazırlanıb; nəticələr avtomatik əldə edilmir. Uyğun məqalə tapdıqda onun URL-ni izləməyə əlavə et.</s-paragraph><s-stack direction="block" gap="base">{(data.opportunities||[]).map(o=><s-link key={o.query} href={o.url} target="_blank">{o.query}</s-link>)}</s-stack></s-section>
 {(data.backlinks||[]).map(b=><s-section key={b.id} heading={new URL(b.url).hostname}><s-link href={b.url} target="_blank">{b.url}</s-link><s-paragraph>{({unchecked:'Yoxlanmayıb',found:'Mağazaya link tapıldı',mention:'Brend adı var, link tapılmadı',missing:'HTML-də link tapılmadı',unknown:'Nəticə məlum deyil'} as Record<string,string>)[b.status]} · {b.checkedAt?new Date(b.checkedAt).toLocaleString('az-AZ'):''}</s-paragraph>{b.links.map((l,i)=><s-paragraph key={i}>{l.anchor||'(mətnsiz link)'} → {l.url} · rel: {l.rel||'nofollow/sponsored qeyd edilməyib'}</s-paragraph>)}<s-paragraph color="subdued">{b.note}</s-paragraph><s-button disabled={busy} onClick={()=>onAction({intent:'backlink-delete',id:b.id})}>Siyahıdan sil</s-button></s-section>)}</>;
}
